;; DO NOT EDIT: File is generated by AWS-SDK/GENERATOR.

(uiop:define-package #:aws-sdk/services/kinesis-video-archived-media
  (:use)
  (:use-reexport #:aws-sdk/services/kinesis-video-archived-media/api))
