;; DO NOT EDIT: File is generated by AWS-SDK/GENERATOR.

(common-lisp:defpackage #:aws-sdk/services/monitoring
  (:nicknames #:aws/monitoring)
  (:import-from #:aws-sdk/generator/shape)
  (:import-from #:aws-sdk/generator/operation)
  (:import-from #:aws-sdk/api))
(common-lisp:in-package #:aws-sdk/services/monitoring)
(common-lisp:deftype action-prefix () 'common-lisp:string)
(common-lisp:deftype actions-enabled () 'common-lisp:boolean)
(common-lisp:deftype alarm-arn () 'common-lisp:string)
(common-lisp:deftype alarm-description () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (alarm-history-item (:copier common-lisp:nil))
   (alarm-name common-lisp:nil :type
    (common-lisp:or alarm-name common-lisp:null))
   (timestamp common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (history-item-type common-lisp:nil :type
    (common-lisp:or history-item-type common-lisp:null))
   (history-summary common-lisp:nil :type
    (common-lisp:or history-summary common-lisp:null))
   (history-data common-lisp:nil :type
    (common-lisp:or history-data common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'alarm-history-item 'make-alarm-history-item))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape alarm-history-item))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "AlarmName"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'alarm-name))
    (aws-sdk/generator/shape::to-query-params "Timestamp"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'timestamp))
    (aws-sdk/generator/shape::to-query-params "HistoryItemType"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'history-item-type))
    (aws-sdk/generator/shape::to-query-params "HistorySummary"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'history-summary))
    (aws-sdk/generator/shape::to-query-params "HistoryData"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'history-data)))))
(common-lisp:progn
 (common-lisp:deftype alarm-history-items ()
   '(trivial-types:proper-list alarm-history-item))
 (common-lisp:defun |make-alarm-history-items|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list alarm-history-item))
   aws-sdk/generator/shape::members))
(common-lisp:deftype alarm-name () 'common-lisp:string)
(common-lisp:deftype alarm-name-prefix () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype alarm-names () '(trivial-types:proper-list alarm-name))
 (common-lisp:defun |make-alarm-names|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list alarm-name))
   aws-sdk/generator/shape::members))
(common-lisp:deftype aws-query-error-message () 'common-lisp:string)
(common-lisp:deftype comparison-operator () 'common-lisp:string)
(common-lisp:deftype dashboard-arn () 'common-lisp:string)
(common-lisp:deftype dashboard-body () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype dashboard-entries ()
   '(trivial-types:proper-list dashboard-entry))
 (common-lisp:defun |make-dashboard-entries|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list dashboard-entry))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (dashboard-entry (:copier common-lisp:nil))
   (dashboard-name common-lisp:nil :type
    (common-lisp:or dashboard-name common-lisp:null))
   (dashboard-arn common-lisp:nil :type
    (common-lisp:or dashboard-arn common-lisp:null))
   (last-modified common-lisp:nil :type
    (common-lisp:or last-modified common-lisp:null))
   (size common-lisp:nil :type (common-lisp:or size common-lisp:null)))
 (common-lisp:export (common-lisp:list 'dashboard-entry 'make-dashboard-entry))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape dashboard-entry))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "DashboardName"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dashboard-name))
    (aws-sdk/generator/shape::to-query-params "DashboardArn"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dashboard-arn))
    (aws-sdk/generator/shape::to-query-params "LastModified"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'last-modified))
    (aws-sdk/generator/shape::to-query-params "Size"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'size)))))
(common-lisp:deftype dashboard-error-message () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct
     (dashboard-invalid-input-error (:copier common-lisp:nil))
   (message common-lisp:nil :type
    (common-lisp:or dashboard-error-message common-lisp:null))
   (dashboard-validation-messages common-lisp:nil :type
    (common-lisp:or dashboard-validation-messages common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'dashboard-invalid-input-error
                    'make-dashboard-invalid-input-error))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          dashboard-invalid-input-error))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "message"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'message))
    (aws-sdk/generator/shape::to-query-params "dashboardValidationMessages"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dashboard-validation-messages)))))
(common-lisp:deftype dashboard-name () 'common-lisp:string)
(common-lisp:deftype dashboard-name-prefix () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype dashboard-names ()
   '(trivial-types:proper-list dashboard-name))
 (common-lisp:defun |make-dashboard-names|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list dashboard-name))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (dashboard-not-found-error (:copier common-lisp:nil))
   (message common-lisp:nil :type
    (common-lisp:or dashboard-error-message common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'dashboard-not-found-error
                    'make-dashboard-not-found-error))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          dashboard-not-found-error))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "message"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'message)))))
(common-lisp:progn
 (common-lisp:defstruct
     (dashboard-validation-message (:copier common-lisp:nil))
   (data-path common-lisp:nil :type
    (common-lisp:or data-path common-lisp:null))
   (message common-lisp:nil :type (common-lisp:or message common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'dashboard-validation-message
                    'make-dashboard-validation-message))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          dashboard-validation-message))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "DataPath"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'data-path))
    (aws-sdk/generator/shape::to-query-params "Message"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'message)))))
(common-lisp:progn
 (common-lisp:deftype dashboard-validation-messages ()
   '(trivial-types:proper-list dashboard-validation-message))
 (common-lisp:defun |make-dashboard-validation-messages|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list
                            dashboard-validation-message))
   aws-sdk/generator/shape::members))
(common-lisp:deftype data-path () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (datapoint (:copier common-lisp:nil))
   (timestamp common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (sample-count common-lisp:nil :type
    (common-lisp:or datapoint-value common-lisp:null))
   (average common-lisp:nil :type
    (common-lisp:or datapoint-value common-lisp:null))
   (sum common-lisp:nil :type
    (common-lisp:or datapoint-value common-lisp:null))
   (minimum common-lisp:nil :type
    (common-lisp:or datapoint-value common-lisp:null))
   (maximum common-lisp:nil :type
    (common-lisp:or datapoint-value common-lisp:null))
   (unit common-lisp:nil :type (common-lisp:or standard-unit common-lisp:null))
   (extended-statistics common-lisp:nil :type
    (common-lisp:or datapoint-value-map common-lisp:null)))
 (common-lisp:export (common-lisp:list 'datapoint 'make-datapoint))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape datapoint))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Timestamp"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'timestamp))
    (aws-sdk/generator/shape::to-query-params "SampleCount"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'sample-count))
    (aws-sdk/generator/shape::to-query-params "Average"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'average))
    (aws-sdk/generator/shape::to-query-params "Sum"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'sum))
    (aws-sdk/generator/shape::to-query-params "Minimum"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'minimum))
    (aws-sdk/generator/shape::to-query-params "Maximum"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'maximum))
    (aws-sdk/generator/shape::to-query-params "Unit"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'unit))
    (aws-sdk/generator/shape::to-query-params "ExtendedStatistics"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'extended-statistics)))))
(common-lisp:deftype datapoint-value () 'common-lisp:double-float)
(common-lisp:defstruct
    (datapoint-value-map
     (:constructor |make-datapoint-value-map|
      (aws-sdk/generator/shape::key aws-sdk/generator/shape::value)))
  aws-sdk/generator/shape::key
  aws-sdk/generator/shape::value)
(common-lisp:progn
 (common-lisp:deftype datapoints () '(trivial-types:proper-list datapoint))
 (common-lisp:defun |make-datapoints|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list datapoint))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (delete-alarms-input (:copier common-lisp:nil))
   (alarm-names (common-lisp:error ":alarm-names is required") :type
    (common-lisp:or alarm-names common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'delete-alarms-input 'make-delete-alarms-input))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape delete-alarms-input))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "AlarmNames"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'alarm-names)))))
(common-lisp:progn
 (common-lisp:defstruct (delete-dashboards-input (:copier common-lisp:nil))
   (dashboard-names common-lisp:nil :type
    (common-lisp:or dashboard-names common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'delete-dashboards-input 'make-delete-dashboards-input))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          delete-dashboards-input))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "DashboardNames"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dashboard-names)))))
(common-lisp:progn
 (common-lisp:defstruct (delete-dashboards-output (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'delete-dashboards-output 'make-delete-dashboards-output))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          delete-dashboards-output))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct
     (describe-alarm-history-input (:copier common-lisp:nil))
   (alarm-name common-lisp:nil :type
    (common-lisp:or alarm-name common-lisp:null))
   (history-item-type common-lisp:nil :type
    (common-lisp:or history-item-type common-lisp:null))
   (start-date common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (end-date common-lisp:nil :type (common-lisp:or timestamp common-lisp:null))
   (max-records common-lisp:nil :type
    (common-lisp:or max-records common-lisp:null))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-alarm-history-input
                    'make-describe-alarm-history-input))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-alarm-history-input))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "AlarmName"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'alarm-name))
    (aws-sdk/generator/shape::to-query-params "HistoryItemType"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'history-item-type))
    (aws-sdk/generator/shape::to-query-params "StartDate"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'start-date))
    (aws-sdk/generator/shape::to-query-params "EndDate"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'end-date))
    (aws-sdk/generator/shape::to-query-params "MaxRecords"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'max-records))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'next-token)))))
(common-lisp:progn
 (common-lisp:defstruct
     (describe-alarm-history-output (:copier common-lisp:nil))
   (alarm-history-items common-lisp:nil :type
    (common-lisp:or alarm-history-items common-lisp:null))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-alarm-history-output
                    'make-describe-alarm-history-output))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-alarm-history-output))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "AlarmHistoryItems"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'alarm-history-items))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'next-token)))))
(common-lisp:progn
 (common-lisp:defstruct
     (describe-alarms-for-metric-input (:copier common-lisp:nil))
   (metric-name (common-lisp:error ":metric-name is required") :type
    (common-lisp:or metric-name common-lisp:null))
   (namespace (common-lisp:error ":namespace is required") :type
    (common-lisp:or namespace common-lisp:null))
   (statistic common-lisp:nil :type
    (common-lisp:or statistic common-lisp:null))
   (extended-statistic common-lisp:nil :type
    (common-lisp:or extended-statistic common-lisp:null))
   (dimensions common-lisp:nil :type
    (common-lisp:or dimensions common-lisp:null))
   (period common-lisp:nil :type (common-lisp:or period common-lisp:null))
   (unit common-lisp:nil :type
    (common-lisp:or standard-unit common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-alarms-for-metric-input
                    'make-describe-alarms-for-metric-input))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-alarms-for-metric-input))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "MetricName"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'metric-name))
    (aws-sdk/generator/shape::to-query-params "Namespace"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'namespace))
    (aws-sdk/generator/shape::to-query-params "Statistic"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'statistic))
    (aws-sdk/generator/shape::to-query-params "ExtendedStatistic"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'extended-statistic))
    (aws-sdk/generator/shape::to-query-params "Dimensions"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dimensions))
    (aws-sdk/generator/shape::to-query-params "Period"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'period))
    (aws-sdk/generator/shape::to-query-params "Unit"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'unit)))))
(common-lisp:progn
 (common-lisp:defstruct
     (describe-alarms-for-metric-output (:copier common-lisp:nil))
   (metric-alarms common-lisp:nil :type
    (common-lisp:or metric-alarms common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-alarms-for-metric-output
                    'make-describe-alarms-for-metric-output))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-alarms-for-metric-output))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "MetricAlarms"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'metric-alarms)))))
(common-lisp:progn
 (common-lisp:defstruct (describe-alarms-input (:copier common-lisp:nil))
   (alarm-names common-lisp:nil :type
    (common-lisp:or alarm-names common-lisp:null))
   (alarm-name-prefix common-lisp:nil :type
    (common-lisp:or alarm-name-prefix common-lisp:null))
   (state-value common-lisp:nil :type
    (common-lisp:or state-value common-lisp:null))
   (action-prefix common-lisp:nil :type
    (common-lisp:or action-prefix common-lisp:null))
   (max-records common-lisp:nil :type
    (common-lisp:or max-records common-lisp:null))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-alarms-input 'make-describe-alarms-input))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-alarms-input))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "AlarmNames"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'alarm-names))
    (aws-sdk/generator/shape::to-query-params "AlarmNamePrefix"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'alarm-name-prefix))
    (aws-sdk/generator/shape::to-query-params "StateValue"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'state-value))
    (aws-sdk/generator/shape::to-query-params "ActionPrefix"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'action-prefix))
    (aws-sdk/generator/shape::to-query-params "MaxRecords"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'max-records))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'next-token)))))
(common-lisp:progn
 (common-lisp:defstruct (describe-alarms-output (:copier common-lisp:nil))
   (metric-alarms common-lisp:nil :type
    (common-lisp:or metric-alarms common-lisp:null))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-alarms-output 'make-describe-alarms-output))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-alarms-output))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "MetricAlarms"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'metric-alarms))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'next-token)))))
(common-lisp:progn
 (common-lisp:defstruct (dimension (:copier common-lisp:nil))
   (name (common-lisp:error ":name is required") :type
    (common-lisp:or dimension-name common-lisp:null))
   (value (common-lisp:error ":value is required") :type
    (common-lisp:or dimension-value common-lisp:null)))
 (common-lisp:export (common-lisp:list 'dimension 'make-dimension))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape dimension))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Name"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'name))
    (aws-sdk/generator/shape::to-query-params "Value"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'value)))))
(common-lisp:progn
 (common-lisp:defstruct (dimension-filter (:copier common-lisp:nil))
   (name (common-lisp:error ":name is required") :type
    (common-lisp:or dimension-name common-lisp:null))
   (value common-lisp:nil :type
    (common-lisp:or dimension-value common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'dimension-filter 'make-dimension-filter))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape dimension-filter))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Name"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'name))
    (aws-sdk/generator/shape::to-query-params "Value"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'value)))))
(common-lisp:progn
 (common-lisp:deftype dimension-filters ()
   '(trivial-types:proper-list dimension-filter))
 (common-lisp:defun |make-dimension-filters|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list dimension-filter))
   aws-sdk/generator/shape::members))
(common-lisp:deftype dimension-name () 'common-lisp:string)
(common-lisp:deftype dimension-value () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype dimensions () '(trivial-types:proper-list dimension))
 (common-lisp:defun |make-dimensions|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list dimension))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (disable-alarm-actions-input (:copier common-lisp:nil))
   (alarm-names (common-lisp:error ":alarm-names is required") :type
    (common-lisp:or alarm-names common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'disable-alarm-actions-input
                    'make-disable-alarm-actions-input))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          disable-alarm-actions-input))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "AlarmNames"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'alarm-names)))))
(common-lisp:progn
 (common-lisp:defstruct (enable-alarm-actions-input (:copier common-lisp:nil))
   (alarm-names (common-lisp:error ":alarm-names is required") :type
    (common-lisp:or alarm-names common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'enable-alarm-actions-input
                    'make-enable-alarm-actions-input))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          enable-alarm-actions-input))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "AlarmNames"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'alarm-names)))))
(common-lisp:deftype error-message () 'common-lisp:string)
(common-lisp:deftype evaluate-low-sample-count-percentile ()
  'common-lisp:string)
(common-lisp:deftype evaluation-periods () 'common-lisp:integer)
(common-lisp:deftype extended-statistic () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype extended-statistics ()
   '(trivial-types:proper-list extended-statistic))
 (common-lisp:defun |make-extended-statistics|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list extended-statistic))
   aws-sdk/generator/shape::members))
(common-lisp:deftype fault-description () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (get-dashboard-input (:copier common-lisp:nil))
   (dashboard-name common-lisp:nil :type
    (common-lisp:or dashboard-name common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-dashboard-input 'make-get-dashboard-input))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape get-dashboard-input))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "DashboardName"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dashboard-name)))))
(common-lisp:progn
 (common-lisp:defstruct (get-dashboard-output (:copier common-lisp:nil))
   (dashboard-arn common-lisp:nil :type
    (common-lisp:or dashboard-arn common-lisp:null))
   (dashboard-body common-lisp:nil :type
    (common-lisp:or dashboard-body common-lisp:null))
   (dashboard-name common-lisp:nil :type
    (common-lisp:or dashboard-name common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-dashboard-output 'make-get-dashboard-output))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape get-dashboard-output))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "DashboardArn"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dashboard-arn))
    (aws-sdk/generator/shape::to-query-params "DashboardBody"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dashboard-body))
    (aws-sdk/generator/shape::to-query-params "DashboardName"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dashboard-name)))))
(common-lisp:progn
 (common-lisp:defstruct (get-metric-statistics-input (:copier common-lisp:nil))
   (namespace (common-lisp:error ":namespace is required") :type
    (common-lisp:or namespace common-lisp:null))
   (metric-name (common-lisp:error ":metric-name is required") :type
    (common-lisp:or metric-name common-lisp:null))
   (dimensions common-lisp:nil :type
    (common-lisp:or dimensions common-lisp:null))
   (start-time (common-lisp:error ":start-time is required") :type
    (common-lisp:or timestamp common-lisp:null))
   (end-time (common-lisp:error ":end-time is required") :type
    (common-lisp:or timestamp common-lisp:null))
   (period (common-lisp:error ":period is required") :type
    (common-lisp:or period common-lisp:null))
   (statistics common-lisp:nil :type
    (common-lisp:or statistics common-lisp:null))
   (extended-statistics common-lisp:nil :type
    (common-lisp:or extended-statistics common-lisp:null))
   (unit common-lisp:nil :type
    (common-lisp:or standard-unit common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-metric-statistics-input
                    'make-get-metric-statistics-input))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          get-metric-statistics-input))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Namespace"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'namespace))
    (aws-sdk/generator/shape::to-query-params "MetricName"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'metric-name))
    (aws-sdk/generator/shape::to-query-params "Dimensions"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dimensions))
    (aws-sdk/generator/shape::to-query-params "StartTime"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'start-time))
    (aws-sdk/generator/shape::to-query-params "EndTime"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'end-time))
    (aws-sdk/generator/shape::to-query-params "Period"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'period))
    (aws-sdk/generator/shape::to-query-params "Statistics"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'statistics))
    (aws-sdk/generator/shape::to-query-params "ExtendedStatistics"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'extended-statistics))
    (aws-sdk/generator/shape::to-query-params "Unit"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'unit)))))
(common-lisp:progn
 (common-lisp:defstruct
     (get-metric-statistics-output (:copier common-lisp:nil))
   (label common-lisp:nil :type (common-lisp:or metric-label common-lisp:null))
   (datapoints common-lisp:nil :type
    (common-lisp:or datapoints common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-metric-statistics-output
                    'make-get-metric-statistics-output))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          get-metric-statistics-output))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Label"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'label))
    (aws-sdk/generator/shape::to-query-params "Datapoints"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'datapoints)))))
(common-lisp:deftype history-data () 'common-lisp:string)
(common-lisp:deftype history-item-type () 'common-lisp:string)
(common-lisp:deftype history-summary () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (internal-service-fault (:copier common-lisp:nil))
   (message common-lisp:nil :type
    (common-lisp:or fault-description common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'internal-service-fault 'make-internal-service-fault))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          internal-service-fault))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Message"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'message)))))
(common-lisp:progn
 (common-lisp:defstruct (invalid-format-fault (:copier common-lisp:nil))
   (message common-lisp:nil :type
    (common-lisp:or error-message common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'invalid-format-fault 'make-invalid-format-fault))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape invalid-format-fault))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "message"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'message)))))
(common-lisp:progn
 (common-lisp:defstruct (invalid-next-token (:copier common-lisp:nil))
   (message common-lisp:nil :type
    (common-lisp:or error-message common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'invalid-next-token 'make-invalid-next-token))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape invalid-next-token))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "message"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'message)))))
(common-lisp:progn
 (common-lisp:defstruct
     (invalid-parameter-combination-exception (:copier common-lisp:nil))
   (message common-lisp:nil :type
    (common-lisp:or aws-query-error-message common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'invalid-parameter-combination-exception
                    'make-invalid-parameter-combination-exception))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          invalid-parameter-combination-exception))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "message"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'message)))))
(common-lisp:progn
 (common-lisp:defstruct
     (invalid-parameter-value-exception (:copier common-lisp:nil))
   (message common-lisp:nil :type
    (common-lisp:or aws-query-error-message common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'invalid-parameter-value-exception
                    'make-invalid-parameter-value-exception))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          invalid-parameter-value-exception))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "message"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'message)))))
(common-lisp:deftype last-modified () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (limit-exceeded-fault (:copier common-lisp:nil))
   (message common-lisp:nil :type
    (common-lisp:or error-message common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'limit-exceeded-fault 'make-limit-exceeded-fault))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape limit-exceeded-fault))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "message"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'message)))))
(common-lisp:progn
 (common-lisp:defstruct (list-dashboards-input (:copier common-lisp:nil))
   (dashboard-name-prefix common-lisp:nil :type
    (common-lisp:or dashboard-name-prefix common-lisp:null))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-dashboards-input 'make-list-dashboards-input))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          list-dashboards-input))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "DashboardNamePrefix"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dashboard-name-prefix))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'next-token)))))
(common-lisp:progn
 (common-lisp:defstruct (list-dashboards-output (:copier common-lisp:nil))
   (dashboard-entries common-lisp:nil :type
    (common-lisp:or dashboard-entries common-lisp:null))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-dashboards-output 'make-list-dashboards-output))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          list-dashboards-output))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "DashboardEntries"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dashboard-entries))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'next-token)))))
(common-lisp:progn
 (common-lisp:defstruct (list-metrics-input (:copier common-lisp:nil))
   (namespace common-lisp:nil :type
    (common-lisp:or namespace common-lisp:null))
   (metric-name common-lisp:nil :type
    (common-lisp:or metric-name common-lisp:null))
   (dimensions common-lisp:nil :type
    (common-lisp:or dimension-filters common-lisp:null))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-metrics-input 'make-list-metrics-input))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape list-metrics-input))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Namespace"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'namespace))
    (aws-sdk/generator/shape::to-query-params "MetricName"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'metric-name))
    (aws-sdk/generator/shape::to-query-params "Dimensions"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dimensions))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'next-token)))))
(common-lisp:progn
 (common-lisp:defstruct (list-metrics-output (:copier common-lisp:nil))
   (metrics common-lisp:nil :type (common-lisp:or metrics common-lisp:null))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-metrics-output 'make-list-metrics-output))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape list-metrics-output))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Metrics"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'metrics))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'next-token)))))
(common-lisp:deftype max-records () 'common-lisp:integer)
(common-lisp:deftype message () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (metric (:copier common-lisp:nil))
   (namespace common-lisp:nil :type
    (common-lisp:or namespace common-lisp:null))
   (metric-name common-lisp:nil :type
    (common-lisp:or metric-name common-lisp:null))
   (dimensions common-lisp:nil :type
    (common-lisp:or dimensions common-lisp:null)))
 (common-lisp:export (common-lisp:list 'metric 'make-metric))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape metric))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Namespace"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'namespace))
    (aws-sdk/generator/shape::to-query-params "MetricName"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'metric-name))
    (aws-sdk/generator/shape::to-query-params "Dimensions"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dimensions)))))
(common-lisp:progn
 (common-lisp:defstruct (metric-alarm (:copier common-lisp:nil))
   (alarm-name common-lisp:nil :type
    (common-lisp:or alarm-name common-lisp:null))
   (alarm-arn common-lisp:nil :type
    (common-lisp:or alarm-arn common-lisp:null))
   (alarm-description common-lisp:nil :type
    (common-lisp:or alarm-description common-lisp:null))
   (alarm-configuration-updated-timestamp common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (actions-enabled common-lisp:nil :type
    (common-lisp:or actions-enabled common-lisp:null))
   (okactions common-lisp:nil :type
    (common-lisp:or resource-list common-lisp:null))
   (alarm-actions common-lisp:nil :type
    (common-lisp:or resource-list common-lisp:null))
   (insufficient-data-actions common-lisp:nil :type
    (common-lisp:or resource-list common-lisp:null))
   (state-value common-lisp:nil :type
    (common-lisp:or state-value common-lisp:null))
   (state-reason common-lisp:nil :type
    (common-lisp:or state-reason common-lisp:null))
   (state-reason-data common-lisp:nil :type
    (common-lisp:or state-reason-data common-lisp:null))
   (state-updated-timestamp common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (metric-name common-lisp:nil :type
    (common-lisp:or metric-name common-lisp:null))
   (namespace common-lisp:nil :type
    (common-lisp:or namespace common-lisp:null))
   (statistic common-lisp:nil :type
    (common-lisp:or statistic common-lisp:null))
   (extended-statistic common-lisp:nil :type
    (common-lisp:or extended-statistic common-lisp:null))
   (dimensions common-lisp:nil :type
    (common-lisp:or dimensions common-lisp:null))
   (period common-lisp:nil :type (common-lisp:or period common-lisp:null))
   (unit common-lisp:nil :type (common-lisp:or standard-unit common-lisp:null))
   (evaluation-periods common-lisp:nil :type
    (common-lisp:or evaluation-periods common-lisp:null))
   (threshold common-lisp:nil :type
    (common-lisp:or threshold common-lisp:null))
   (comparison-operator common-lisp:nil :type
    (common-lisp:or comparison-operator common-lisp:null))
   (treat-missing-data common-lisp:nil :type
    (common-lisp:or treat-missing-data common-lisp:null))
   (evaluate-low-sample-count-percentile common-lisp:nil :type
    (common-lisp:or evaluate-low-sample-count-percentile common-lisp:null)))
 (common-lisp:export (common-lisp:list 'metric-alarm 'make-metric-alarm))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape metric-alarm))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "AlarmName"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'alarm-name))
    (aws-sdk/generator/shape::to-query-params "AlarmArn"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'alarm-arn))
    (aws-sdk/generator/shape::to-query-params "AlarmDescription"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'alarm-description))
    (aws-sdk/generator/shape::to-query-params
     "AlarmConfigurationUpdatedTimestamp"
     (common-lisp:slot-value aws-sdk/generator/shape::shape
                             'alarm-configuration-updated-timestamp))
    (aws-sdk/generator/shape::to-query-params "ActionsEnabled"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'actions-enabled))
    (aws-sdk/generator/shape::to-query-params "OKActions"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'okactions))
    (aws-sdk/generator/shape::to-query-params "AlarmActions"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'alarm-actions))
    (aws-sdk/generator/shape::to-query-params "InsufficientDataActions"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'insufficient-data-actions))
    (aws-sdk/generator/shape::to-query-params "StateValue"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'state-value))
    (aws-sdk/generator/shape::to-query-params "StateReason"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'state-reason))
    (aws-sdk/generator/shape::to-query-params "StateReasonData"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'state-reason-data))
    (aws-sdk/generator/shape::to-query-params "StateUpdatedTimestamp"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'state-updated-timestamp))
    (aws-sdk/generator/shape::to-query-params "MetricName"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'metric-name))
    (aws-sdk/generator/shape::to-query-params "Namespace"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'namespace))
    (aws-sdk/generator/shape::to-query-params "Statistic"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'statistic))
    (aws-sdk/generator/shape::to-query-params "ExtendedStatistic"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'extended-statistic))
    (aws-sdk/generator/shape::to-query-params "Dimensions"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dimensions))
    (aws-sdk/generator/shape::to-query-params "Period"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'period))
    (aws-sdk/generator/shape::to-query-params "Unit"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'unit))
    (aws-sdk/generator/shape::to-query-params "EvaluationPeriods"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'evaluation-periods))
    (aws-sdk/generator/shape::to-query-params "Threshold"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'threshold))
    (aws-sdk/generator/shape::to-query-params "ComparisonOperator"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'comparison-operator))
    (aws-sdk/generator/shape::to-query-params "TreatMissingData"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'treat-missing-data))
    (aws-sdk/generator/shape::to-query-params
     "EvaluateLowSampleCountPercentile"
     (common-lisp:slot-value aws-sdk/generator/shape::shape
                             'evaluate-low-sample-count-percentile)))))
(common-lisp:progn
 (common-lisp:deftype metric-alarms ()
   '(trivial-types:proper-list metric-alarm))
 (common-lisp:defun |make-metric-alarms|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list metric-alarm))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:deftype metric-data () '(trivial-types:proper-list metric-datum))
 (common-lisp:defun |make-metric-data|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list metric-datum))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (metric-datum (:copier common-lisp:nil))
   (metric-name (common-lisp:error ":metric-name is required") :type
    (common-lisp:or metric-name common-lisp:null))
   (dimensions common-lisp:nil :type
    (common-lisp:or dimensions common-lisp:null))
   (timestamp common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (value common-lisp:nil :type
    (common-lisp:or datapoint-value common-lisp:null))
   (statistic-values common-lisp:nil :type
    (common-lisp:or statistic-set common-lisp:null))
   (unit common-lisp:nil :type (common-lisp:or standard-unit common-lisp:null))
   (storage-resolution common-lisp:nil :type
    (common-lisp:or storage-resolution common-lisp:null)))
 (common-lisp:export (common-lisp:list 'metric-datum 'make-metric-datum))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape metric-datum))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "MetricName"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'metric-name))
    (aws-sdk/generator/shape::to-query-params "Dimensions"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dimensions))
    (aws-sdk/generator/shape::to-query-params "Timestamp"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'timestamp))
    (aws-sdk/generator/shape::to-query-params "Value"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'value))
    (aws-sdk/generator/shape::to-query-params "StatisticValues"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'statistic-values))
    (aws-sdk/generator/shape::to-query-params "Unit"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'unit))
    (aws-sdk/generator/shape::to-query-params "StorageResolution"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'storage-resolution)))))
(common-lisp:deftype metric-label () 'common-lisp:string)
(common-lisp:deftype metric-name () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype metrics () '(trivial-types:proper-list metric))
 (common-lisp:defun |make-metrics|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list metric))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct
     (missing-required-parameter-exception (:copier common-lisp:nil))
   (message common-lisp:nil :type
    (common-lisp:or aws-query-error-message common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'missing-required-parameter-exception
                    'make-missing-required-parameter-exception))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          missing-required-parameter-exception))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "message"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'message)))))
(common-lisp:deftype namespace () 'common-lisp:string)
(common-lisp:deftype next-token () 'common-lisp:string)
(common-lisp:deftype period () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:defstruct (put-dashboard-input (:copier common-lisp:nil))
   (dashboard-name common-lisp:nil :type
    (common-lisp:or dashboard-name common-lisp:null))
   (dashboard-body common-lisp:nil :type
    (common-lisp:or dashboard-body common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'put-dashboard-input 'make-put-dashboard-input))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape put-dashboard-input))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "DashboardName"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dashboard-name))
    (aws-sdk/generator/shape::to-query-params "DashboardBody"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dashboard-body)))))
(common-lisp:progn
 (common-lisp:defstruct (put-dashboard-output (:copier common-lisp:nil))
   (dashboard-validation-messages common-lisp:nil :type
    (common-lisp:or dashboard-validation-messages common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'put-dashboard-output 'make-put-dashboard-output))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape put-dashboard-output))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "DashboardValidationMessages"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dashboard-validation-messages)))))
(common-lisp:progn
 (common-lisp:defstruct (put-metric-alarm-input (:copier common-lisp:nil))
   (alarm-name (common-lisp:error ":alarm-name is required") :type
    (common-lisp:or alarm-name common-lisp:null))
   (alarm-description common-lisp:nil :type
    (common-lisp:or alarm-description common-lisp:null))
   (actions-enabled common-lisp:nil :type
    (common-lisp:or actions-enabled common-lisp:null))
   (okactions common-lisp:nil :type
    (common-lisp:or resource-list common-lisp:null))
   (alarm-actions common-lisp:nil :type
    (common-lisp:or resource-list common-lisp:null))
   (insufficient-data-actions common-lisp:nil :type
    (common-lisp:or resource-list common-lisp:null))
   (metric-name (common-lisp:error ":metric-name is required") :type
    (common-lisp:or metric-name common-lisp:null))
   (namespace (common-lisp:error ":namespace is required") :type
    (common-lisp:or namespace common-lisp:null))
   (statistic common-lisp:nil :type
    (common-lisp:or statistic common-lisp:null))
   (extended-statistic common-lisp:nil :type
    (common-lisp:or extended-statistic common-lisp:null))
   (dimensions common-lisp:nil :type
    (common-lisp:or dimensions common-lisp:null))
   (period (common-lisp:error ":period is required") :type
    (common-lisp:or period common-lisp:null))
   (unit common-lisp:nil :type (common-lisp:or standard-unit common-lisp:null))
   (evaluation-periods (common-lisp:error ":evaluation-periods is required")
    :type (common-lisp:or evaluation-periods common-lisp:null))
   (threshold (common-lisp:error ":threshold is required") :type
    (common-lisp:or threshold common-lisp:null))
   (comparison-operator (common-lisp:error ":comparison-operator is required")
    :type (common-lisp:or comparison-operator common-lisp:null))
   (treat-missing-data common-lisp:nil :type
    (common-lisp:or treat-missing-data common-lisp:null))
   (evaluate-low-sample-count-percentile common-lisp:nil :type
    (common-lisp:or evaluate-low-sample-count-percentile common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'put-metric-alarm-input 'make-put-metric-alarm-input))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          put-metric-alarm-input))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "AlarmName"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'alarm-name))
    (aws-sdk/generator/shape::to-query-params "AlarmDescription"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'alarm-description))
    (aws-sdk/generator/shape::to-query-params "ActionsEnabled"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'actions-enabled))
    (aws-sdk/generator/shape::to-query-params "OKActions"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'okactions))
    (aws-sdk/generator/shape::to-query-params "AlarmActions"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'alarm-actions))
    (aws-sdk/generator/shape::to-query-params "InsufficientDataActions"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'insufficient-data-actions))
    (aws-sdk/generator/shape::to-query-params "MetricName"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'metric-name))
    (aws-sdk/generator/shape::to-query-params "Namespace"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'namespace))
    (aws-sdk/generator/shape::to-query-params "Statistic"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'statistic))
    (aws-sdk/generator/shape::to-query-params "ExtendedStatistic"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'extended-statistic))
    (aws-sdk/generator/shape::to-query-params "Dimensions"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'dimensions))
    (aws-sdk/generator/shape::to-query-params "Period"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'period))
    (aws-sdk/generator/shape::to-query-params "Unit"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'unit))
    (aws-sdk/generator/shape::to-query-params "EvaluationPeriods"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'evaluation-periods))
    (aws-sdk/generator/shape::to-query-params "Threshold"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'threshold))
    (aws-sdk/generator/shape::to-query-params "ComparisonOperator"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'comparison-operator))
    (aws-sdk/generator/shape::to-query-params "TreatMissingData"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'treat-missing-data))
    (aws-sdk/generator/shape::to-query-params
     "EvaluateLowSampleCountPercentile"
     (common-lisp:slot-value aws-sdk/generator/shape::shape
                             'evaluate-low-sample-count-percentile)))))
(common-lisp:progn
 (common-lisp:defstruct (put-metric-data-input (:copier common-lisp:nil))
   (namespace (common-lisp:error ":namespace is required") :type
    (common-lisp:or namespace common-lisp:null))
   (metric-data (common-lisp:error ":metric-data is required") :type
    (common-lisp:or metric-data common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'put-metric-data-input 'make-put-metric-data-input))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          put-metric-data-input))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Namespace"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'namespace))
    (aws-sdk/generator/shape::to-query-params "MetricData"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'metric-data)))))
(common-lisp:progn
 (common-lisp:deftype resource-list ()
   '(trivial-types:proper-list resource-name))
 (common-lisp:defun |make-resource-list|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list resource-name))
   aws-sdk/generator/shape::members))
(common-lisp:deftype resource-name () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (resource-not-found (:copier common-lisp:nil))
   (message common-lisp:nil :type
    (common-lisp:or error-message common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'resource-not-found 'make-resource-not-found))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape resource-not-found))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "message"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'message)))))
(common-lisp:progn
 (common-lisp:defstruct (set-alarm-state-input (:copier common-lisp:nil))
   (alarm-name (common-lisp:error ":alarm-name is required") :type
    (common-lisp:or alarm-name common-lisp:null))
   (state-value (common-lisp:error ":state-value is required") :type
    (common-lisp:or state-value common-lisp:null))
   (state-reason (common-lisp:error ":state-reason is required") :type
    (common-lisp:or state-reason common-lisp:null))
   (state-reason-data common-lisp:nil :type
    (common-lisp:or state-reason-data common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'set-alarm-state-input 'make-set-alarm-state-input))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          set-alarm-state-input))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "AlarmName"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'alarm-name))
    (aws-sdk/generator/shape::to-query-params "StateValue"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'state-value))
    (aws-sdk/generator/shape::to-query-params "StateReason"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'state-reason))
    (aws-sdk/generator/shape::to-query-params "StateReasonData"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'state-reason-data)))))
(common-lisp:deftype size () 'common-lisp:integer)
(common-lisp:deftype standard-unit () 'common-lisp:string)
(common-lisp:deftype state-reason () 'common-lisp:string)
(common-lisp:deftype state-reason-data () 'common-lisp:string)
(common-lisp:deftype state-value () 'common-lisp:string)
(common-lisp:deftype statistic () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (statistic-set (:copier common-lisp:nil))
   (sample-count (common-lisp:error ":sample-count is required") :type
    (common-lisp:or datapoint-value common-lisp:null))
   (sum (common-lisp:error ":sum is required") :type
    (common-lisp:or datapoint-value common-lisp:null))
   (minimum (common-lisp:error ":minimum is required") :type
    (common-lisp:or datapoint-value common-lisp:null))
   (maximum (common-lisp:error ":maximum is required") :type
    (common-lisp:or datapoint-value common-lisp:null)))
 (common-lisp:export (common-lisp:list 'statistic-set 'make-statistic-set))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape statistic-set))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "SampleCount"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'sample-count))
    (aws-sdk/generator/shape::to-query-params "Sum"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'sum))
    (aws-sdk/generator/shape::to-query-params "Minimum"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'minimum))
    (aws-sdk/generator/shape::to-query-params "Maximum"
                                              (common-lisp:slot-value
                                               aws-sdk/generator/shape::shape
                                               'maximum)))))
(common-lisp:progn
 (common-lisp:deftype statistics () '(trivial-types:proper-list statistic))
 (common-lisp:defun |make-statistics|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list statistic))
   aws-sdk/generator/shape::members))
(common-lisp:deftype storage-resolution () 'common-lisp:integer)
(common-lisp:deftype threshold () 'common-lisp:double-float)
(common-lisp:deftype timestamp () 'common-lisp:string)
(common-lisp:deftype treat-missing-data () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defun delete-alarms
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key alarm-names)
   (common-lisp:declare (common-lisp:ignorable alarm-names))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-delete-alarms-input
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "monitoring" :method :post :params
                               (common-lisp:cons `("Action" ,@"DeleteAlarms")
                                                 (aws-sdk/generator/shape:shape-to-params
                                                  aws-sdk/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'delete-alarms))
(common-lisp:progn
 (common-lisp:defun delete-dashboards
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key dashboard-names)
   (common-lisp:declare (common-lisp:ignorable dashboard-names))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-delete-dashboards-input
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "monitoring" :method :post :params
                               (common-lisp:cons
                                `("Action" ,@"DeleteDashboards")
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "DeleteDashboardsOutput" "DeleteDashboardsResult")))
 (common-lisp:export 'delete-dashboards))
(common-lisp:progn
 (common-lisp:defun describe-alarm-history
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key alarm-name history-item-type start-date
                     end-date max-records next-token)
   (common-lisp:declare
    (common-lisp:ignorable alarm-name history-item-type start-date end-date
     max-records next-token))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-describe-alarm-history-input
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "monitoring" :method :post :params
                               (common-lisp:cons
                                `("Action" ,@"DescribeAlarmHistory")
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "DescribeAlarmHistoryOutput" "DescribeAlarmHistoryResult")))
 (common-lisp:export 'describe-alarm-history))
(common-lisp:progn
 (common-lisp:defun describe-alarms
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key alarm-names alarm-name-prefix state-value
                     action-prefix max-records next-token)
   (common-lisp:declare
    (common-lisp:ignorable alarm-names alarm-name-prefix state-value
     action-prefix max-records next-token))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-describe-alarms-input
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "monitoring" :method :post :params
                               (common-lisp:cons `("Action" ,@"DescribeAlarms")
                                                 (aws-sdk/generator/shape:shape-to-params
                                                  aws-sdk/generator/operation::input)))
      "DescribeAlarmsOutput" "DescribeAlarmsResult")))
 (common-lisp:export 'describe-alarms))
(common-lisp:progn
 (common-lisp:defun describe-alarms-for-metric
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key metric-name namespace statistic
                     extended-statistic dimensions period unit)
   (common-lisp:declare
    (common-lisp:ignorable metric-name namespace statistic extended-statistic
     dimensions period unit))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-describe-alarms-for-metric-input
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "monitoring" :method :post :params
                               (common-lisp:cons
                                `("Action" ,@"DescribeAlarmsForMetric")
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "DescribeAlarmsForMetricOutput" "DescribeAlarmsForMetricResult")))
 (common-lisp:export 'describe-alarms-for-metric))
(common-lisp:progn
 (common-lisp:defun disable-alarm-actions
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key alarm-names)
   (common-lisp:declare (common-lisp:ignorable alarm-names))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-disable-alarm-actions-input
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "monitoring" :method :post :params
                               (common-lisp:cons
                                `("Action" ,@"DisableAlarmActions")
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'disable-alarm-actions))
(common-lisp:progn
 (common-lisp:defun enable-alarm-actions
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key alarm-names)
   (common-lisp:declare (common-lisp:ignorable alarm-names))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-enable-alarm-actions-input
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "monitoring" :method :post :params
                               (common-lisp:cons
                                `("Action" ,@"EnableAlarmActions")
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'enable-alarm-actions))
(common-lisp:progn
 (common-lisp:defun get-dashboard
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key dashboard-name)
   (common-lisp:declare (common-lisp:ignorable dashboard-name))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-get-dashboard-input
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "monitoring" :method :post :params
                               (common-lisp:cons `("Action" ,@"GetDashboard")
                                                 (aws-sdk/generator/shape:shape-to-params
                                                  aws-sdk/generator/operation::input)))
      "GetDashboardOutput" "GetDashboardResult")))
 (common-lisp:export 'get-dashboard))
(common-lisp:progn
 (common-lisp:defun get-metric-statistics
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key namespace metric-name dimensions
                     start-time end-time period statistics extended-statistics
                     unit)
   (common-lisp:declare
    (common-lisp:ignorable namespace metric-name dimensions start-time end-time
     period statistics extended-statistics unit))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-get-metric-statistics-input
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "monitoring" :method :post :params
                               (common-lisp:cons
                                `("Action" ,@"GetMetricStatistics")
                                (aws-sdk/generator/shape:shape-to-params
                                 aws-sdk/generator/operation::input)))
      "GetMetricStatisticsOutput" "GetMetricStatisticsResult")))
 (common-lisp:export 'get-metric-statistics))
(common-lisp:progn
 (common-lisp:defun list-dashboards
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key dashboard-name-prefix next-token)
   (common-lisp:declare
    (common-lisp:ignorable dashboard-name-prefix next-token))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-list-dashboards-input
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "monitoring" :method :post :params
                               (common-lisp:cons `("Action" ,@"ListDashboards")
                                                 (aws-sdk/generator/shape:shape-to-params
                                                  aws-sdk/generator/operation::input)))
      "ListDashboardsOutput" "ListDashboardsResult")))
 (common-lisp:export 'list-dashboards))
(common-lisp:progn
 (common-lisp:defun list-metrics
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key namespace metric-name dimensions
                     next-token)
   (common-lisp:declare
    (common-lisp:ignorable namespace metric-name dimensions next-token))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-list-metrics-input
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "monitoring" :method :post :params
                               (common-lisp:cons `("Action" ,@"ListMetrics")
                                                 (aws-sdk/generator/shape:shape-to-params
                                                  aws-sdk/generator/operation::input)))
      "ListMetricsOutput" "ListMetricsResult")))
 (common-lisp:export 'list-metrics))
(common-lisp:progn
 (common-lisp:defun put-dashboard
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key dashboard-name dashboard-body)
   (common-lisp:declare (common-lisp:ignorable dashboard-name dashboard-body))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-put-dashboard-input
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "monitoring" :method :post :params
                               (common-lisp:cons `("Action" ,@"PutDashboard")
                                                 (aws-sdk/generator/shape:shape-to-params
                                                  aws-sdk/generator/operation::input)))
      "PutDashboardOutput" "PutDashboardResult")))
 (common-lisp:export 'put-dashboard))
(common-lisp:progn
 (common-lisp:defun put-metric-alarm
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key alarm-name alarm-description
                     actions-enabled okactions alarm-actions
                     insufficient-data-actions metric-name namespace statistic
                     extended-statistic dimensions period unit
                     evaluation-periods threshold comparison-operator
                     treat-missing-data evaluate-low-sample-count-percentile)
   (common-lisp:declare
    (common-lisp:ignorable alarm-name alarm-description actions-enabled
     okactions alarm-actions insufficient-data-actions metric-name namespace
     statistic extended-statistic dimensions period unit evaluation-periods
     threshold comparison-operator treat-missing-data
     evaluate-low-sample-count-percentile))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-put-metric-alarm-input
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "monitoring" :method :post :params
                               (common-lisp:cons `("Action" ,@"PutMetricAlarm")
                                                 (aws-sdk/generator/shape:shape-to-params
                                                  aws-sdk/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'put-metric-alarm))
(common-lisp:progn
 (common-lisp:defun put-metric-data
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key namespace metric-data)
   (common-lisp:declare (common-lisp:ignorable namespace metric-data))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-put-metric-data-input
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "monitoring" :method :post :params
                               (common-lisp:cons `("Action" ,@"PutMetricData")
                                                 (aws-sdk/generator/shape:shape-to-params
                                                  aws-sdk/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'put-metric-data))
(common-lisp:progn
 (common-lisp:defun set-alarm-state
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key alarm-name state-value state-reason
                     state-reason-data)
   (common-lisp:declare
    (common-lisp:ignorable alarm-name state-value state-reason
     state-reason-data))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-set-alarm-state-input
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request :service "monitoring" :method :post :params
                               (common-lisp:cons `("Action" ,@"SetAlarmState")
                                                 (aws-sdk/generator/shape:shape-to-params
                                                  aws-sdk/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'set-alarm-state))
