;; DO NOT EDIT: File is generated by AWS-SDK/GENERATOR.

(common-lisp:defpackage #:aws-sdk/services/sso-oidc/api
  (:use)
  (:nicknames #:aws/sso-oidc)
  (:import-from #:aws-sdk/generator/shape)
  (:import-from #:aws-sdk/generator/operation)
  (:import-from #:aws-sdk/api)
  (:import-from #:aws-sdk/request)
  (:import-from #:aws-sdk/json-request)
  (:import-from #:aws-sdk/rest-json-request)
  (:import-from #:aws-sdk/rest-xml-request)
  (:import-from #:aws-sdk/query-request)
  (:import-from #:aws-sdk/error))
(common-lisp:in-package #:aws-sdk/services/sso-oidc/api)
(common-lisp:progn
 (common-lisp:define-condition sso-oidc-error
     (aws-sdk/error:aws-error)
     common-lisp:nil)
 (common-lisp:export 'sso-oidc-error))
(common-lisp:progn
 (common-lisp:defclass sso-oidc-request
                       (aws-sdk/generator/service::rest-json-request)
                       common-lisp:nil
                       (:default-initargs :service "sso-oidc" :api-version
                        "2019-06-10" :host-prefix "oidc" :signing-name
                        "sso-oauth" :global-host common-lisp:nil))
 (common-lisp:export 'sso-oidc-request))
(common-lisp:defvar *error-map*
  '(("AccessDeniedException" . access-denied-exception)
    ("AuthorizationPendingException" . authorization-pending-exception)
    ("ExpiredTokenException" . expired-token-exception)
    ("InternalServerException" . internal-server-exception)
    ("InvalidClientException" . invalid-client-exception)
    ("InvalidClientMetadataException" . invalid-client-metadata-exception)
    ("InvalidGrantException" . invalid-grant-exception)
    ("InvalidRequestException" . invalid-request-exception)
    ("InvalidRequestRegionException" . invalid-request-region-exception)
    ("InvalidScopeException" . invalid-scope-exception)
    ("SlowDownException" . slow-down-exception)
    ("UnauthorizedClientException" . unauthorized-client-exception)
    ("UnsupportedGrantTypeException" . unsupported-grant-type-exception)))
(common-lisp:progn
 (common-lisp:define-condition access-denied-exception
     (sso-oidc-error)
     ((error :initarg :error :initform common-lisp:nil :reader
       access-denied-exception-error)
      (error-description :initarg :error-description :initform common-lisp:nil
       :reader access-denied-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'access-denied-exception 'access-denied-exception-error
                    'access-denied-exception-error-description)))
(common-lisp:deftype access-token () 'common-lisp:string)
(common-lisp:deftype assertion () 'common-lisp:string)
(common-lisp:deftype auth-code () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:define-condition authorization-pending-exception
     (sso-oidc-error)
     ((error :initarg :error :initform common-lisp:nil :reader
       authorization-pending-exception-error)
      (error-description :initarg :error-description :initform common-lisp:nil
       :reader authorization-pending-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'authorization-pending-exception
                    'authorization-pending-exception-error
                    'authorization-pending-exception-error-description)))
(common-lisp:deftype client-id () 'common-lisp:string)
(common-lisp:deftype client-name () 'common-lisp:string)
(common-lisp:deftype client-secret () 'common-lisp:string)
(common-lisp:deftype client-type () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defclass create-token-request common-lisp:nil
                       ((client-id :initarg :client-id :initform
                         (common-lisp:error ":clientid is required") :type
                         (common-lisp:or client-id common-lisp:null) :accessor
                         struct-shape-create-token-request-client-id :shape
                         "ClientId" :location common-lisp:nil :location-name
                         common-lisp:nil)
                        (client-secret :initarg :client-secret :initform
                         (common-lisp:error ":clientsecret is required") :type
                         (common-lisp:or client-secret common-lisp:null)
                         :accessor
                         struct-shape-create-token-request-client-secret :shape
                         "ClientSecret" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (grant-type :initarg :grant-type :initform
                         (common-lisp:error ":granttype is required") :type
                         (common-lisp:or grant-type common-lisp:null) :accessor
                         struct-shape-create-token-request-grant-type :shape
                         "GrantType" :location common-lisp:nil :location-name
                         common-lisp:nil)
                        (device-code :initarg :device-code :initform
                         common-lisp:nil :type
                         (common-lisp:or device-code common-lisp:null)
                         :accessor
                         struct-shape-create-token-request-device-code :shape
                         "DeviceCode" :location common-lisp:nil :location-name
                         common-lisp:nil)
                        (code :initarg :code :initform common-lisp:nil :type
                         (common-lisp:or auth-code common-lisp:null) :accessor
                         struct-shape-create-token-request-code :shape
                         "AuthCode" :location common-lisp:nil :location-name
                         common-lisp:nil)
                        (refresh-token :initarg :refresh-token :initform
                         common-lisp:nil :type
                         (common-lisp:or refresh-token common-lisp:null)
                         :accessor
                         struct-shape-create-token-request-refresh-token :shape
                         "RefreshToken" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (scope :initarg :scope :initform common-lisp:nil :type
                         (common-lisp:or scopes common-lisp:null) :accessor
                         struct-shape-create-token-request-scope :shape
                         "Scopes" :location common-lisp:nil :location-name
                         common-lisp:nil)
                        (redirect-uri :initarg :redirect-uri :initform
                         common-lisp:nil :type
                         (common-lisp:or uri common-lisp:null) :accessor
                         struct-shape-create-token-request-redirect-uri :shape
                         "URI" :location common-lisp:nil :location-name
                         common-lisp:nil))
                       (:metaclass aws-sdk/generator/shape::members-class))
 (common-lisp:defun make-create-token-request
                    (common-lisp:&rest aws-sdk/generator/shape::args)
   (common-lisp:apply #'common-lisp:make-instance 'create-token-request
                      aws-sdk/generator/shape::args))
 (common-lisp:export
  (common-lisp:list 'create-token-request 'make-create-token-request))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        ((aws-sdk/generator/shape::input create-token-request))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        ((aws-sdk/generator/shape::input create-token-request))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-id))
      (common-lisp:list
       (common-lisp:cons "clientId"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-secret))
      (common-lisp:list
       (common-lisp:cons "clientSecret"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'grant-type))
      (common-lisp:list
       (common-lisp:cons "grantType"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'device-code))
      (common-lisp:list
       (common-lisp:cons "deviceCode"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'code))
      (common-lisp:list
       (common-lisp:cons "code"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'refresh-token))
      (common-lisp:list
       (common-lisp:cons "refreshToken"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'scope))
      (common-lisp:list
       (common-lisp:cons "scope"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'redirect-uri))
      (common-lisp:list
       (common-lisp:cons "redirectUri"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        ((aws-sdk/generator/shape::input create-token-request))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:defclass create-token-response common-lisp:nil
                       ((access-token :initarg :access-token :initform
                         common-lisp:nil :type
                         (common-lisp:or access-token common-lisp:null)
                         :accessor
                         struct-shape-create-token-response-access-token :shape
                         "AccessToken" :location common-lisp:nil :location-name
                         common-lisp:nil)
                        (token-type :initarg :token-type :initform
                         common-lisp:nil :type
                         (common-lisp:or token-type common-lisp:null) :accessor
                         struct-shape-create-token-response-token-type :shape
                         "TokenType" :location common-lisp:nil :location-name
                         common-lisp:nil)
                        (expires-in :initarg :expires-in :initform
                         common-lisp:nil :type
                         (common-lisp:or expiration-in-seconds
                                         common-lisp:null)
                         :accessor
                         struct-shape-create-token-response-expires-in :shape
                         "ExpirationInSeconds" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (refresh-token :initarg :refresh-token :initform
                         common-lisp:nil :type
                         (common-lisp:or refresh-token common-lisp:null)
                         :accessor
                         struct-shape-create-token-response-refresh-token
                         :shape "RefreshToken" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (id-token :initarg :id-token :initform common-lisp:nil
                         :type (common-lisp:or id-token common-lisp:null)
                         :accessor struct-shape-create-token-response-id-token
                         :shape "IdToken" :location common-lisp:nil
                         :location-name common-lisp:nil))
                       (:metaclass aws-sdk/generator/shape::members-class))
 (common-lisp:defun make-create-token-response
                    (common-lisp:&rest aws-sdk/generator/shape::args)
   (common-lisp:apply #'common-lisp:make-instance 'create-token-response
                      aws-sdk/generator/shape::args))
 (common-lisp:export
  (common-lisp:list 'create-token-response 'make-create-token-response))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          create-token-response))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          create-token-response))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'access-token))
      (common-lisp:list
       (common-lisp:cons "accessToken"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'token-type))
      (common-lisp:list
       (common-lisp:cons "tokenType"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'expires-in))
      (common-lisp:list
       (common-lisp:cons "expiresIn"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'refresh-token))
      (common-lisp:list
       (common-lisp:cons "refreshToken"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'id-token))
      (common-lisp:list
       (common-lisp:cons "idToken"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          create-token-response))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:defclass create-token-with-iamrequest common-lisp:nil
                       ((client-id :initarg :client-id :initform
                         (common-lisp:error ":clientid is required") :type
                         (common-lisp:or client-id common-lisp:null) :accessor
                         struct-shape-create-token-with-iamrequest-client-id
                         :shape "ClientId" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (grant-type :initarg :grant-type :initform
                         (common-lisp:error ":granttype is required") :type
                         (common-lisp:or grant-type common-lisp:null) :accessor
                         struct-shape-create-token-with-iamrequest-grant-type
                         :shape "GrantType" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (code :initarg :code :initform common-lisp:nil :type
                         (common-lisp:or auth-code common-lisp:null) :accessor
                         struct-shape-create-token-with-iamrequest-code :shape
                         "AuthCode" :location common-lisp:nil :location-name
                         common-lisp:nil)
                        (refresh-token :initarg :refresh-token :initform
                         common-lisp:nil :type
                         (common-lisp:or refresh-token common-lisp:null)
                         :accessor
                         struct-shape-create-token-with-iamrequest-refresh-token
                         :shape "RefreshToken" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (assertion :initarg :assertion :initform
                         common-lisp:nil :type
                         (common-lisp:or assertion common-lisp:null) :accessor
                         struct-shape-create-token-with-iamrequest-assertion
                         :shape "Assertion" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (scope :initarg :scope :initform common-lisp:nil :type
                         (common-lisp:or scopes common-lisp:null) :accessor
                         struct-shape-create-token-with-iamrequest-scope :shape
                         "Scopes" :location common-lisp:nil :location-name
                         common-lisp:nil)
                        (redirect-uri :initarg :redirect-uri :initform
                         common-lisp:nil :type
                         (common-lisp:or uri common-lisp:null) :accessor
                         struct-shape-create-token-with-iamrequest-redirect-uri
                         :shape "URI" :location common-lisp:nil :location-name
                         common-lisp:nil)
                        (subject-token :initarg :subject-token :initform
                         common-lisp:nil :type
                         (common-lisp:or subject-token common-lisp:null)
                         :accessor
                         struct-shape-create-token-with-iamrequest-subject-token
                         :shape "SubjectToken" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (subject-token-type :initarg :subject-token-type
                         :initform common-lisp:nil :type
                         (common-lisp:or token-type-uri common-lisp:null)
                         :accessor
                         struct-shape-create-token-with-iamrequest-subject-token-type
                         :shape "TokenTypeURI" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (requested-token-type :initarg :requested-token-type
                         :initform common-lisp:nil :type
                         (common-lisp:or token-type-uri common-lisp:null)
                         :accessor
                         struct-shape-create-token-with-iamrequest-requested-token-type
                         :shape "TokenTypeURI" :location common-lisp:nil
                         :location-name common-lisp:nil))
                       (:metaclass aws-sdk/generator/shape::members-class))
 (common-lisp:defun make-create-token-with-iamrequest
                    (common-lisp:&rest aws-sdk/generator/shape::args)
   (common-lisp:apply #'common-lisp:make-instance 'create-token-with-iamrequest
                      aws-sdk/generator/shape::args))
 (common-lisp:export
  (common-lisp:list 'create-token-with-iamrequest
                    'make-create-token-with-iamrequest))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          create-token-with-iamrequest))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          create-token-with-iamrequest))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-id))
      (common-lisp:list
       (common-lisp:cons "clientId"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'grant-type))
      (common-lisp:list
       (common-lisp:cons "grantType"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'code))
      (common-lisp:list
       (common-lisp:cons "code"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'refresh-token))
      (common-lisp:list
       (common-lisp:cons "refreshToken"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'assertion))
      (common-lisp:list
       (common-lisp:cons "assertion"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'scope))
      (common-lisp:list
       (common-lisp:cons "scope"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'redirect-uri))
      (common-lisp:list
       (common-lisp:cons "redirectUri"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'subject-token))
      (common-lisp:list
       (common-lisp:cons "subjectToken"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'subject-token-type))
      (common-lisp:list
       (common-lisp:cons "subjectTokenType"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input
                           'requested-token-type))
      (common-lisp:list
       (common-lisp:cons "requestedTokenType"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          create-token-with-iamrequest))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:defclass create-token-with-iamresponse common-lisp:nil
                       ((access-token :initarg :access-token :initform
                         common-lisp:nil :type
                         (common-lisp:or access-token common-lisp:null)
                         :accessor
                         struct-shape-create-token-with-iamresponse-access-token
                         :shape "AccessToken" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (token-type :initarg :token-type :initform
                         common-lisp:nil :type
                         (common-lisp:or token-type common-lisp:null) :accessor
                         struct-shape-create-token-with-iamresponse-token-type
                         :shape "TokenType" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (expires-in :initarg :expires-in :initform
                         common-lisp:nil :type
                         (common-lisp:or expiration-in-seconds
                                         common-lisp:null)
                         :accessor
                         struct-shape-create-token-with-iamresponse-expires-in
                         :shape "ExpirationInSeconds" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (refresh-token :initarg :refresh-token :initform
                         common-lisp:nil :type
                         (common-lisp:or refresh-token common-lisp:null)
                         :accessor
                         struct-shape-create-token-with-iamresponse-refresh-token
                         :shape "RefreshToken" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (id-token :initarg :id-token :initform common-lisp:nil
                         :type (common-lisp:or id-token common-lisp:null)
                         :accessor
                         struct-shape-create-token-with-iamresponse-id-token
                         :shape "IdToken" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (issued-token-type :initarg :issued-token-type
                         :initform common-lisp:nil :type
                         (common-lisp:or token-type-uri common-lisp:null)
                         :accessor
                         struct-shape-create-token-with-iamresponse-issued-token-type
                         :shape "TokenTypeURI" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (scope :initarg :scope :initform common-lisp:nil :type
                         (common-lisp:or scopes common-lisp:null) :accessor
                         struct-shape-create-token-with-iamresponse-scope
                         :shape "Scopes" :location common-lisp:nil
                         :location-name common-lisp:nil))
                       (:metaclass aws-sdk/generator/shape::members-class))
 (common-lisp:defun make-create-token-with-iamresponse
                    (common-lisp:&rest aws-sdk/generator/shape::args)
   (common-lisp:apply #'common-lisp:make-instance
                      'create-token-with-iamresponse
                      aws-sdk/generator/shape::args))
 (common-lisp:export
  (common-lisp:list 'create-token-with-iamresponse
                    'make-create-token-with-iamresponse))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          create-token-with-iamresponse))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          create-token-with-iamresponse))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'access-token))
      (common-lisp:list
       (common-lisp:cons "accessToken"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'token-type))
      (common-lisp:list
       (common-lisp:cons "tokenType"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'expires-in))
      (common-lisp:list
       (common-lisp:cons "expiresIn"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'refresh-token))
      (common-lisp:list
       (common-lisp:cons "refreshToken"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'id-token))
      (common-lisp:list
       (common-lisp:cons "idToken"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'issued-token-type))
      (common-lisp:list
       (common-lisp:cons "issuedTokenType"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'scope))
      (common-lisp:list
       (common-lisp:cons "scope"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          create-token-with-iamresponse))
   common-lisp:nil))
(common-lisp:deftype device-code () 'common-lisp:string)
(common-lisp:deftype error () 'common-lisp:string)
(common-lisp:deftype error-description () 'common-lisp:string)
(common-lisp:deftype expiration-in-seconds () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:define-condition expired-token-exception
     (sso-oidc-error)
     ((error :initarg :error :initform common-lisp:nil :reader
       expired-token-exception-error)
      (error-description :initarg :error-description :initform common-lisp:nil
       :reader expired-token-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'expired-token-exception 'expired-token-exception-error
                    'expired-token-exception-error-description)))
(common-lisp:deftype grant-type () 'common-lisp:string)
(common-lisp:deftype id-token () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:define-condition internal-server-exception
     (sso-oidc-error)
     ((error :initarg :error :initform common-lisp:nil :reader
       internal-server-exception-error)
      (error-description :initarg :error-description :initform common-lisp:nil
       :reader internal-server-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'internal-server-exception 'internal-server-exception-error
                    'internal-server-exception-error-description)))
(common-lisp:deftype interval-in-seconds () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:define-condition invalid-client-exception
     (sso-oidc-error)
     ((error :initarg :error :initform common-lisp:nil :reader
       invalid-client-exception-error)
      (error-description :initarg :error-description :initform common-lisp:nil
       :reader invalid-client-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'invalid-client-exception 'invalid-client-exception-error
                    'invalid-client-exception-error-description)))
(common-lisp:progn
 (common-lisp:define-condition invalid-client-metadata-exception
     (sso-oidc-error)
     ((error :initarg :error :initform common-lisp:nil :reader
       invalid-client-metadata-exception-error)
      (error-description :initarg :error-description :initform common-lisp:nil
       :reader invalid-client-metadata-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'invalid-client-metadata-exception
                    'invalid-client-metadata-exception-error
                    'invalid-client-metadata-exception-error-description)))
(common-lisp:progn
 (common-lisp:define-condition invalid-grant-exception
     (sso-oidc-error)
     ((error :initarg :error :initform common-lisp:nil :reader
       invalid-grant-exception-error)
      (error-description :initarg :error-description :initform common-lisp:nil
       :reader invalid-grant-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'invalid-grant-exception 'invalid-grant-exception-error
                    'invalid-grant-exception-error-description)))
(common-lisp:progn
 (common-lisp:define-condition invalid-request-exception
     (sso-oidc-error)
     ((error :initarg :error :initform common-lisp:nil :reader
       invalid-request-exception-error)
      (error-description :initarg :error-description :initform common-lisp:nil
       :reader invalid-request-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'invalid-request-exception 'invalid-request-exception-error
                    'invalid-request-exception-error-description)))
(common-lisp:progn
 (common-lisp:define-condition invalid-request-region-exception
     (sso-oidc-error)
     ((error :initarg :error :initform common-lisp:nil :reader
       invalid-request-region-exception-error)
      (error-description :initarg :error-description :initform common-lisp:nil
       :reader invalid-request-region-exception-error-description)
      (endpoint :initarg :endpoint :initform common-lisp:nil :reader
       invalid-request-region-exception-endpoint)
      (region :initarg :region :initform common-lisp:nil :reader
       invalid-request-region-exception-region)))
 (common-lisp:export
  (common-lisp:list 'invalid-request-region-exception
                    'invalid-request-region-exception-error
                    'invalid-request-region-exception-error-description
                    'invalid-request-region-exception-endpoint
                    'invalid-request-region-exception-region)))
(common-lisp:progn
 (common-lisp:define-condition invalid-scope-exception
     (sso-oidc-error)
     ((error :initarg :error :initform common-lisp:nil :reader
       invalid-scope-exception-error)
      (error-description :initarg :error-description :initform common-lisp:nil
       :reader invalid-scope-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'invalid-scope-exception 'invalid-scope-exception-error
                    'invalid-scope-exception-error-description)))
(common-lisp:deftype location () 'common-lisp:string)
(common-lisp:deftype long-time-stamp-type () 'common-lisp:integer)
(common-lisp:deftype refresh-token () 'common-lisp:string)
(common-lisp:deftype region () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defclass register-client-request common-lisp:nil
                       ((client-name :initarg :client-name :initform
                         (common-lisp:error ":clientname is required") :type
                         (common-lisp:or client-name common-lisp:null)
                         :accessor
                         struct-shape-register-client-request-client-name
                         :shape "ClientName" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (client-type :initarg :client-type :initform
                         (common-lisp:error ":clienttype is required") :type
                         (common-lisp:or client-type common-lisp:null)
                         :accessor
                         struct-shape-register-client-request-client-type
                         :shape "ClientType" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (scopes :initarg :scopes :initform common-lisp:nil
                         :type (common-lisp:or scopes common-lisp:null)
                         :accessor struct-shape-register-client-request-scopes
                         :shape "Scopes" :location common-lisp:nil
                         :location-name common-lisp:nil))
                       (:metaclass aws-sdk/generator/shape::members-class))
 (common-lisp:defun make-register-client-request
                    (common-lisp:&rest aws-sdk/generator/shape::args)
   (common-lisp:apply #'common-lisp:make-instance 'register-client-request
                      aws-sdk/generator/shape::args))
 (common-lisp:export
  (common-lisp:list 'register-client-request 'make-register-client-request))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          register-client-request))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          register-client-request))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-name))
      (common-lisp:list
       (common-lisp:cons "clientName"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-type))
      (common-lisp:list
       (common-lisp:cons "clientType"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'scopes))
      (common-lisp:list
       (common-lisp:cons "scopes"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          register-client-request))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:defclass register-client-response common-lisp:nil
                       ((client-id :initarg :client-id :initform
                         common-lisp:nil :type
                         (common-lisp:or client-id common-lisp:null) :accessor
                         struct-shape-register-client-response-client-id :shape
                         "ClientId" :location common-lisp:nil :location-name
                         common-lisp:nil)
                        (client-secret :initarg :client-secret :initform
                         common-lisp:nil :type
                         (common-lisp:or client-secret common-lisp:null)
                         :accessor
                         struct-shape-register-client-response-client-secret
                         :shape "ClientSecret" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (client-id-issued-at :initarg :client-id-issued-at
                         :initform common-lisp:nil :type
                         (common-lisp:or long-time-stamp-type common-lisp:null)
                         :accessor
                         struct-shape-register-client-response-client-id-issued-at
                         :shape "LongTimeStampType" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (client-secret-expires-at :initarg
                         :client-secret-expires-at :initform common-lisp:nil
                         :type
                         (common-lisp:or long-time-stamp-type common-lisp:null)
                         :accessor
                         struct-shape-register-client-response-client-secret-expires-at
                         :shape "LongTimeStampType" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (authorization-endpoint :initarg
                         :authorization-endpoint :initform common-lisp:nil
                         :type (common-lisp:or uri common-lisp:null) :accessor
                         struct-shape-register-client-response-authorization-endpoint
                         :shape "URI" :location common-lisp:nil :location-name
                         common-lisp:nil)
                        (token-endpoint :initarg :token-endpoint :initform
                         common-lisp:nil :type
                         (common-lisp:or uri common-lisp:null) :accessor
                         struct-shape-register-client-response-token-endpoint
                         :shape "URI" :location common-lisp:nil :location-name
                         common-lisp:nil))
                       (:metaclass aws-sdk/generator/shape::members-class))
 (common-lisp:defun make-register-client-response
                    (common-lisp:&rest aws-sdk/generator/shape::args)
   (common-lisp:apply #'common-lisp:make-instance 'register-client-response
                      aws-sdk/generator/shape::args))
 (common-lisp:export
  (common-lisp:list 'register-client-response 'make-register-client-response))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          register-client-response))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          register-client-response))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-id))
      (common-lisp:list
       (common-lisp:cons "clientId"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-secret))
      (common-lisp:list
       (common-lisp:cons "clientSecret"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-id-issued-at))
      (common-lisp:list
       (common-lisp:cons "clientIdIssuedAt"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input
                           'client-secret-expires-at))
      (common-lisp:list
       (common-lisp:cons "clientSecretExpiresAt"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input
                           'authorization-endpoint))
      (common-lisp:list
       (common-lisp:cons "authorizationEndpoint"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'token-endpoint))
      (common-lisp:list
       (common-lisp:cons "tokenEndpoint"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          register-client-response))
   common-lisp:nil))
(common-lisp:deftype scope () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype scopes () '(trivial-types:proper-list scope))
 (common-lisp:defun make-scopes
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list scope))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:define-condition slow-down-exception
     (sso-oidc-error)
     ((error :initarg :error :initform common-lisp:nil :reader
       slow-down-exception-error)
      (error-description :initarg :error-description :initform common-lisp:nil
       :reader slow-down-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'slow-down-exception 'slow-down-exception-error
                    'slow-down-exception-error-description)))
(common-lisp:progn
 (common-lisp:defclass start-device-authorization-request common-lisp:nil
                       ((client-id :initarg :client-id :initform
                         (common-lisp:error ":clientid is required") :type
                         (common-lisp:or client-id common-lisp:null) :accessor
                         struct-shape-start-device-authorization-request-client-id
                         :shape "ClientId" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (client-secret :initarg :client-secret :initform
                         (common-lisp:error ":clientsecret is required") :type
                         (common-lisp:or client-secret common-lisp:null)
                         :accessor
                         struct-shape-start-device-authorization-request-client-secret
                         :shape "ClientSecret" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (start-url :initarg :start-url :initform
                         (common-lisp:error ":starturl is required") :type
                         (common-lisp:or uri common-lisp:null) :accessor
                         struct-shape-start-device-authorization-request-start-url
                         :shape "URI" :location common-lisp:nil :location-name
                         common-lisp:nil))
                       (:metaclass aws-sdk/generator/shape::members-class))
 (common-lisp:defun make-start-device-authorization-request
                    (common-lisp:&rest aws-sdk/generator/shape::args)
   (common-lisp:apply #'common-lisp:make-instance
                      'start-device-authorization-request
                      aws-sdk/generator/shape::args))
 (common-lisp:export
  (common-lisp:list 'start-device-authorization-request
                    'make-start-device-authorization-request))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          start-device-authorization-request))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          start-device-authorization-request))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-id))
      (common-lisp:list
       (common-lisp:cons "clientId"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'client-secret))
      (common-lisp:list
       (common-lisp:cons "clientSecret"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'start-url))
      (common-lisp:list
       (common-lisp:cons "startUrl"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          start-device-authorization-request))
   common-lisp:nil))
(common-lisp:progn
 (common-lisp:defclass start-device-authorization-response common-lisp:nil
                       ((device-code :initarg :device-code :initform
                         common-lisp:nil :type
                         (common-lisp:or device-code common-lisp:null)
                         :accessor
                         struct-shape-start-device-authorization-response-device-code
                         :shape "DeviceCode" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (user-code :initarg :user-code :initform
                         common-lisp:nil :type
                         (common-lisp:or user-code common-lisp:null) :accessor
                         struct-shape-start-device-authorization-response-user-code
                         :shape "UserCode" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (verification-uri :initarg :verification-uri :initform
                         common-lisp:nil :type
                         (common-lisp:or uri common-lisp:null) :accessor
                         struct-shape-start-device-authorization-response-verification-uri
                         :shape "URI" :location common-lisp:nil :location-name
                         common-lisp:nil)
                        (verification-uri-complete :initarg
                         :verification-uri-complete :initform common-lisp:nil
                         :type (common-lisp:or uri common-lisp:null) :accessor
                         struct-shape-start-device-authorization-response-verification-uri-complete
                         :shape "URI" :location common-lisp:nil :location-name
                         common-lisp:nil)
                        (expires-in :initarg :expires-in :initform
                         common-lisp:nil :type
                         (common-lisp:or expiration-in-seconds
                                         common-lisp:null)
                         :accessor
                         struct-shape-start-device-authorization-response-expires-in
                         :shape "ExpirationInSeconds" :location common-lisp:nil
                         :location-name common-lisp:nil)
                        (interval :initarg :interval :initform common-lisp:nil
                         :type
                         (common-lisp:or interval-in-seconds common-lisp:null)
                         :accessor
                         struct-shape-start-device-authorization-response-interval
                         :shape "IntervalInSeconds" :location common-lisp:nil
                         :location-name common-lisp:nil))
                       (:metaclass aws-sdk/generator/shape::members-class))
 (common-lisp:defun make-start-device-authorization-response
                    (common-lisp:&rest aws-sdk/generator/shape::args)
   (common-lisp:apply #'common-lisp:make-instance
                      'start-device-authorization-response
                      aws-sdk/generator/shape::args))
 (common-lisp:export
  (common-lisp:list 'start-device-authorization-response
                    'make-start-device-authorization-response))
 (common-lisp:defmethod aws-sdk/generator/shape::input-headers
                        (
                         (aws-sdk/generator/shape::input
                          start-device-authorization-response))
   (common-lisp:append))
 (common-lisp:defmethod aws-sdk/generator/shape::input-params
                        (
                         (aws-sdk/generator/shape::input
                          start-device-authorization-response))
   (common-lisp:append
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'device-code))
      (common-lisp:list
       (common-lisp:cons "deviceCode"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'user-code))
      (common-lisp:list
       (common-lisp:cons "userCode"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'verification-uri))
      (common-lisp:list
       (common-lisp:cons "verificationUri"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input
                           'verification-uri-complete))
      (common-lisp:list
       (common-lisp:cons "verificationUriComplete"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'expires-in))
      (common-lisp:list
       (common-lisp:cons "expiresIn"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))
    (alexandria:when-let (aws-sdk/generator/shape::value
                          (common-lisp:slot-value
                           aws-sdk/generator/shape::input 'interval))
      (common-lisp:list
       (common-lisp:cons "interval"
                         (aws-sdk/generator/shape::input-params
                          aws-sdk/generator/shape::value))))))
 (common-lisp:defmethod aws-sdk/generator/shape::input-payload
                        (
                         (aws-sdk/generator/shape::input
                          start-device-authorization-response))
   common-lisp:nil))
(common-lisp:deftype subject-token () 'common-lisp:string)
(common-lisp:deftype token-type () 'common-lisp:string)
(common-lisp:deftype token-type-uri () 'common-lisp:string)
(common-lisp:deftype uri () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:define-condition unauthorized-client-exception
     (sso-oidc-error)
     ((error :initarg :error :initform common-lisp:nil :reader
       unauthorized-client-exception-error)
      (error-description :initarg :error-description :initform common-lisp:nil
       :reader unauthorized-client-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'unauthorized-client-exception
                    'unauthorized-client-exception-error
                    'unauthorized-client-exception-error-description)))
(common-lisp:progn
 (common-lisp:define-condition unsupported-grant-type-exception
     (sso-oidc-error)
     ((error :initarg :error :initform common-lisp:nil :reader
       unsupported-grant-type-exception-error)
      (error-description :initarg :error-description :initform common-lisp:nil
       :reader unsupported-grant-type-exception-error-description)))
 (common-lisp:export
  (common-lisp:list 'unsupported-grant-type-exception
                    'unsupported-grant-type-exception-error
                    'unsupported-grant-type-exception-error-description)))
(common-lisp:deftype user-code () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defun create-token
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key client-id client-secret grant-type
                     device-code code refresh-token scope redirect-uri)
   (common-lisp:declare
    (common-lisp:ignorable client-id client-secret grant-type device-code code
     refresh-token scope redirect-uri))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-create-token-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (aws-sdk/generator/shape:make-request-with-input 'sso-oidc-request
                                                        aws-sdk/generator/operation::input
                                                        "POST" "/token"
                                                        "CreateToken"))
      common-lisp:nil common-lisp:nil *error-map*)))
 (common-lisp:export 'create-token))
(common-lisp:progn
 (common-lisp:defun create-token-with-iam
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key client-id grant-type code refresh-token
                     assertion scope redirect-uri subject-token
                     subject-token-type requested-token-type)
   (common-lisp:declare
    (common-lisp:ignorable client-id grant-type code refresh-token assertion
     scope redirect-uri subject-token subject-token-type requested-token-type))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-create-token-with-iamrequest
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (aws-sdk/generator/shape:make-request-with-input 'sso-oidc-request
                                                        aws-sdk/generator/operation::input
                                                        "POST"
                                                        "/token?aws_iam=t"
                                                        "CreateTokenWithIAM"))
      common-lisp:nil common-lisp:nil *error-map*)))
 (common-lisp:export 'create-token-with-iam))
(common-lisp:progn
 (common-lisp:defun register-client
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key client-name client-type scopes)
   (common-lisp:declare (common-lisp:ignorable client-name client-type scopes))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-register-client-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (aws-sdk/generator/shape:make-request-with-input 'sso-oidc-request
                                                        aws-sdk/generator/operation::input
                                                        "POST"
                                                        "/client/register"
                                                        "RegisterClient"))
      common-lisp:nil common-lisp:nil *error-map*)))
 (common-lisp:export 'register-client))
(common-lisp:progn
 (common-lisp:defun start-device-authorization
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key client-id client-secret start-url)
   (common-lisp:declare
    (common-lisp:ignorable client-id client-secret start-url))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply
                       'make-start-device-authorization-request
                       aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (aws-sdk/generator/shape:make-request-with-input 'sso-oidc-request
                                                        aws-sdk/generator/operation::input
                                                        "POST"
                                                        "/device_authorization"
                                                        "StartDeviceAuthorization"))
      common-lisp:nil common-lisp:nil *error-map*)))
 (common-lisp:export 'start-device-authorization))
