;; DO NOT EDIT: File is generated by AWS-SDK/GENERATOR.

(common-lisp:defpackage #:aws-sdk/services/opsworkscm/api
  (:use)
  (:nicknames #:aws/opsworkscm)
  (:import-from #:aws-sdk/generator/shape)
  (:import-from #:aws-sdk/generator/operation)
  (:import-from #:aws-sdk/api)
  (:import-from #:aws-sdk/request))
(common-lisp:in-package #:aws-sdk/services/opsworkscm/api)
(common-lisp:progn
 (common-lisp:defclass opsworkscm-request (aws-sdk/request:request)
                       common-lisp:nil
                       (:default-initargs :service "opsworkscm"))
 (common-lisp:export 'opsworkscm-request))
(common-lisp:progn
 (common-lisp:defstruct (account-attribute (:copier common-lisp:nil))
   (name common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (maximum common-lisp:nil :type (common-lisp:or integer common-lisp:null))
   (used common-lisp:nil :type (common-lisp:or integer common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'account-attribute 'make-account-attribute))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape account-attribute))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Name"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'name)))
    (aws-sdk/generator/shape::to-query-params "Maximum"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'maximum)))
    (aws-sdk/generator/shape::to-query-params "Used"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'used))))))
(common-lisp:progn
 (common-lisp:deftype account-attributes ()
   '(trivial-types:proper-list account-attribute))
 (common-lisp:defun |make-account-attributes|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list account-attribute))
   aws-sdk/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (associate-node-request (:copier common-lisp:nil))
   (server-name (common-lisp:error ":server-name is required") :type
    (common-lisp:or server-name common-lisp:null))
   (node-name (common-lisp:error ":node-name is required") :type
    (common-lisp:or node-name common-lisp:null))
   (engine-attributes (common-lisp:error ":engine-attributes is required")
    :type (common-lisp:or engine-attributes common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'associate-node-request 'make-associate-node-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          associate-node-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ServerName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server-name)))
    (aws-sdk/generator/shape::to-query-params "NodeName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'node-name)))
    (aws-sdk/generator/shape::to-query-params "EngineAttributes"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'engine-attributes))))))
(common-lisp:progn
 (common-lisp:defstruct (associate-node-response (:copier common-lisp:nil))
   (node-association-status-token common-lisp:nil :type
    (common-lisp:or node-association-status-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'associate-node-response 'make-associate-node-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          associate-node-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "NodeAssociationStatusToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'node-association-status-token))))))
(common-lisp:deftype attribute-name () 'common-lisp:string)
(common-lisp:deftype attribute-value () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (backup (:copier common-lisp:nil))
   (backup-arn common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (backup-id common-lisp:nil :type
    (common-lisp:or backup-id common-lisp:null))
   (backup-type common-lisp:nil :type
    (common-lisp:or backup-type common-lisp:null))
   (created-at common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (description common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (engine common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (engine-model common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (engine-version common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (instance-profile-arn common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (instance-type common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (key-pair common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (preferred-backup-window common-lisp:nil :type
    (common-lisp:or time-window-definition common-lisp:null))
   (preferred-maintenance-window common-lisp:nil :type
    (common-lisp:or time-window-definition common-lisp:null))
   (s3data-size common-lisp:nil :type
    (common-lisp:or integer common-lisp:null))
   (s3data-url common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (s3log-url common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (security-group-ids common-lisp:nil :type
    (common-lisp:or strings common-lisp:null))
   (server-name common-lisp:nil :type
    (common-lisp:or server-name common-lisp:null))
   (service-role-arn common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (status common-lisp:nil :type
    (common-lisp:or backup-status common-lisp:null))
   (status-description common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (subnet-ids common-lisp:nil :type (common-lisp:or strings common-lisp:null))
   (tools-version common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (user-arn common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export (common-lisp:list 'backup 'make-backup))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape backup))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "BackupArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'backup-arn)))
    (aws-sdk/generator/shape::to-query-params "BackupId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'backup-id)))
    (aws-sdk/generator/shape::to-query-params "BackupType"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'backup-type)))
    (aws-sdk/generator/shape::to-query-params "CreatedAt"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'created-at)))
    (aws-sdk/generator/shape::to-query-params "Description"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'description)))
    (aws-sdk/generator/shape::to-query-params "Engine"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'engine)))
    (aws-sdk/generator/shape::to-query-params "EngineModel"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'engine-model)))
    (aws-sdk/generator/shape::to-query-params "EngineVersion"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'engine-version)))
    (aws-sdk/generator/shape::to-query-params "InstanceProfileArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'instance-profile-arn)))
    (aws-sdk/generator/shape::to-query-params "InstanceType"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'instance-type)))
    (aws-sdk/generator/shape::to-query-params "KeyPair"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'key-pair)))
    (aws-sdk/generator/shape::to-query-params "PreferredBackupWindow"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'preferred-backup-window)))
    (aws-sdk/generator/shape::to-query-params "PreferredMaintenanceWindow"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'preferred-maintenance-window)))
    (aws-sdk/generator/shape::to-query-params "S3DataSize"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                's3data-size)))
    (aws-sdk/generator/shape::to-query-params "S3DataUrl"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                's3data-url)))
    (aws-sdk/generator/shape::to-query-params "S3LogUrl"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                's3log-url)))
    (aws-sdk/generator/shape::to-query-params "SecurityGroupIds"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'security-group-ids)))
    (aws-sdk/generator/shape::to-query-params "ServerName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server-name)))
    (aws-sdk/generator/shape::to-query-params "ServiceRoleArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'service-role-arn)))
    (aws-sdk/generator/shape::to-query-params "Status"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'status)))
    (aws-sdk/generator/shape::to-query-params "StatusDescription"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'status-description)))
    (aws-sdk/generator/shape::to-query-params "SubnetIds"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'subnet-ids)))
    (aws-sdk/generator/shape::to-query-params "ToolsVersion"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'tools-version)))
    (aws-sdk/generator/shape::to-query-params "UserArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'user-arn))))))
(common-lisp:deftype backup-id () 'common-lisp:string)
(common-lisp:deftype backup-retention-count-definition () 'common-lisp:integer)
(common-lisp:deftype backup-status () 'common-lisp:string)
(common-lisp:deftype backup-type () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype backups () '(trivial-types:proper-list backup))
 (common-lisp:defun |make-backups|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list backup))
   aws-sdk/generator/shape::members))
(common-lisp:deftype boolean () 'common-lisp:boolean)
(common-lisp:progn
 (common-lisp:defstruct (create-backup-request (:copier common-lisp:nil))
   (server-name (common-lisp:error ":server-name is required") :type
    (common-lisp:or server-name common-lisp:null))
   (description common-lisp:nil :type
    (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'create-backup-request 'make-create-backup-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          create-backup-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ServerName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server-name)))
    (aws-sdk/generator/shape::to-query-params "Description"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'description))))))
(common-lisp:progn
 (common-lisp:defstruct (create-backup-response (:copier common-lisp:nil))
   (backup common-lisp:nil :type (common-lisp:or backup common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'create-backup-response 'make-create-backup-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          create-backup-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Backup"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'backup))))))
(common-lisp:progn
 (common-lisp:defstruct (create-server-request (:copier common-lisp:nil))
   (associate-public-ip-address common-lisp:nil :type
    (common-lisp:or boolean common-lisp:null))
   (disable-automated-backup common-lisp:nil :type
    (common-lisp:or boolean common-lisp:null))
   (engine common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (engine-model common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (engine-version common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (engine-attributes common-lisp:nil :type
    (common-lisp:or engine-attributes common-lisp:null))
   (backup-retention-count common-lisp:nil :type
    (common-lisp:or backup-retention-count-definition common-lisp:null))
   (server-name (common-lisp:error ":server-name is required") :type
    (common-lisp:or server-name common-lisp:null))
   (instance-profile-arn
    (common-lisp:error ":instance-profile-arn is required") :type
    (common-lisp:or instance-profile-arn common-lisp:null))
   (instance-type (common-lisp:error ":instance-type is required") :type
    (common-lisp:or string common-lisp:null))
   (key-pair common-lisp:nil :type (common-lisp:or key-pair common-lisp:null))
   (preferred-maintenance-window common-lisp:nil :type
    (common-lisp:or time-window-definition common-lisp:null))
   (preferred-backup-window common-lisp:nil :type
    (common-lisp:or time-window-definition common-lisp:null))
   (security-group-ids common-lisp:nil :type
    (common-lisp:or strings common-lisp:null))
   (service-role-arn (common-lisp:error ":service-role-arn is required") :type
    (common-lisp:or service-role-arn common-lisp:null))
   (subnet-ids common-lisp:nil :type (common-lisp:or strings common-lisp:null))
   (backup-id common-lisp:nil :type
    (common-lisp:or backup-id common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'create-server-request 'make-create-server-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          create-server-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "AssociatePublicIpAddress"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'associate-public-ip-address)))
    (aws-sdk/generator/shape::to-query-params "DisableAutomatedBackup"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'disable-automated-backup)))
    (aws-sdk/generator/shape::to-query-params "Engine"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'engine)))
    (aws-sdk/generator/shape::to-query-params "EngineModel"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'engine-model)))
    (aws-sdk/generator/shape::to-query-params "EngineVersion"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'engine-version)))
    (aws-sdk/generator/shape::to-query-params "EngineAttributes"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'engine-attributes)))
    (aws-sdk/generator/shape::to-query-params "BackupRetentionCount"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'backup-retention-count)))
    (aws-sdk/generator/shape::to-query-params "ServerName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server-name)))
    (aws-sdk/generator/shape::to-query-params "InstanceProfileArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'instance-profile-arn)))
    (aws-sdk/generator/shape::to-query-params "InstanceType"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'instance-type)))
    (aws-sdk/generator/shape::to-query-params "KeyPair"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'key-pair)))
    (aws-sdk/generator/shape::to-query-params "PreferredMaintenanceWindow"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'preferred-maintenance-window)))
    (aws-sdk/generator/shape::to-query-params "PreferredBackupWindow"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'preferred-backup-window)))
    (aws-sdk/generator/shape::to-query-params "SecurityGroupIds"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'security-group-ids)))
    (aws-sdk/generator/shape::to-query-params "ServiceRoleArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'service-role-arn)))
    (aws-sdk/generator/shape::to-query-params "SubnetIds"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'subnet-ids)))
    (aws-sdk/generator/shape::to-query-params "BackupId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'backup-id))))))
(common-lisp:progn
 (common-lisp:defstruct (create-server-response (:copier common-lisp:nil))
   (server common-lisp:nil :type (common-lisp:or server common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'create-server-response 'make-create-server-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          create-server-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Server"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server))))))
(common-lisp:progn
 (common-lisp:defstruct (delete-backup-request (:copier common-lisp:nil))
   (backup-id (common-lisp:error ":backup-id is required") :type
    (common-lisp:or backup-id common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'delete-backup-request 'make-delete-backup-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          delete-backup-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "BackupId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'backup-id))))))
(common-lisp:progn
 (common-lisp:defstruct (delete-backup-response (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'delete-backup-response 'make-delete-backup-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          delete-backup-response))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct (delete-server-request (:copier common-lisp:nil))
   (server-name (common-lisp:error ":server-name is required") :type
    (common-lisp:or server-name common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'delete-server-request 'make-delete-server-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          delete-server-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ServerName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server-name))))))
(common-lisp:progn
 (common-lisp:defstruct (delete-server-response (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'delete-server-response 'make-delete-server-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          delete-server-response))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct
     (describe-account-attributes-request (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'describe-account-attributes-request
                    'make-describe-account-attributes-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-account-attributes-request))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct
     (describe-account-attributes-response (:copier common-lisp:nil))
   (attributes common-lisp:nil :type
    (common-lisp:or account-attributes common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-account-attributes-response
                    'make-describe-account-attributes-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-account-attributes-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Attributes"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'attributes))))))
(common-lisp:progn
 (common-lisp:defstruct (describe-backups-request (:copier common-lisp:nil))
   (backup-id common-lisp:nil :type
    (common-lisp:or backup-id common-lisp:null))
   (server-name common-lisp:nil :type
    (common-lisp:or server-name common-lisp:null))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token common-lisp:null))
   (max-results common-lisp:nil :type
    (common-lisp:or max-results common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-backups-request 'make-describe-backups-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-backups-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "BackupId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'backup-id)))
    (aws-sdk/generator/shape::to-query-params "ServerName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server-name)))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "MaxResults"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'max-results))))))
(common-lisp:progn
 (common-lisp:defstruct (describe-backups-response (:copier common-lisp:nil))
   (backups common-lisp:nil :type (common-lisp:or backups common-lisp:null))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-backups-response
                    'make-describe-backups-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-backups-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Backups"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'backups)))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token))))))
(common-lisp:progn
 (common-lisp:defstruct (describe-events-request (:copier common-lisp:nil))
   (server-name (common-lisp:error ":server-name is required") :type
    (common-lisp:or server-name common-lisp:null))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token common-lisp:null))
   (max-results common-lisp:nil :type
    (common-lisp:or max-results common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-events-request 'make-describe-events-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-events-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ServerName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server-name)))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "MaxResults"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'max-results))))))
(common-lisp:progn
 (common-lisp:defstruct (describe-events-response (:copier common-lisp:nil))
   (server-events common-lisp:nil :type
    (common-lisp:or server-events common-lisp:null))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-events-response 'make-describe-events-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-events-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ServerEvents"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server-events)))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token))))))
(common-lisp:progn
 (common-lisp:defstruct
     (describe-node-association-status-request (:copier common-lisp:nil))
   (node-association-status-token
    (common-lisp:error ":node-association-status-token is required") :type
    (common-lisp:or node-association-status-token common-lisp:null))
   (server-name (common-lisp:error ":server-name is required") :type
    (common-lisp:or server-name common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-node-association-status-request
                    'make-describe-node-association-status-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-node-association-status-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "NodeAssociationStatusToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'node-association-status-token)))
    (aws-sdk/generator/shape::to-query-params "ServerName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server-name))))))
(common-lisp:progn
 (common-lisp:defstruct
     (describe-node-association-status-response (:copier common-lisp:nil))
   (node-association-status common-lisp:nil :type
    (common-lisp:or node-association-status common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-node-association-status-response
                    'make-describe-node-association-status-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-node-association-status-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "NodeAssociationStatus"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'node-association-status))))))
(common-lisp:progn
 (common-lisp:defstruct (describe-servers-request (:copier common-lisp:nil))
   (server-name common-lisp:nil :type
    (common-lisp:or server-name common-lisp:null))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token common-lisp:null))
   (max-results common-lisp:nil :type
    (common-lisp:or max-results common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-servers-request 'make-describe-servers-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-servers-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ServerName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server-name)))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token)))
    (aws-sdk/generator/shape::to-query-params "MaxResults"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'max-results))))))
(common-lisp:progn
 (common-lisp:defstruct (describe-servers-response (:copier common-lisp:nil))
   (servers common-lisp:nil :type (common-lisp:or servers common-lisp:null))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-servers-response
                    'make-describe-servers-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          describe-servers-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Servers"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'servers)))
    (aws-sdk/generator/shape::to-query-params "NextToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'next-token))))))
(common-lisp:progn
 (common-lisp:defstruct (disassociate-node-request (:copier common-lisp:nil))
   (server-name (common-lisp:error ":server-name is required") :type
    (common-lisp:or server-name common-lisp:null))
   (node-name (common-lisp:error ":node-name is required") :type
    (common-lisp:or node-name common-lisp:null))
   (engine-attributes common-lisp:nil :type
    (common-lisp:or engine-attributes common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'disassociate-node-request
                    'make-disassociate-node-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          disassociate-node-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ServerName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server-name)))
    (aws-sdk/generator/shape::to-query-params "NodeName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'node-name)))
    (aws-sdk/generator/shape::to-query-params "EngineAttributes"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'engine-attributes))))))
(common-lisp:progn
 (common-lisp:defstruct (disassociate-node-response (:copier common-lisp:nil))
   (node-association-status-token common-lisp:nil :type
    (common-lisp:or node-association-status-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'disassociate-node-response
                    'make-disassociate-node-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          disassociate-node-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "NodeAssociationStatusToken"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'node-association-status-token))))))
(common-lisp:progn
 (common-lisp:defstruct (engine-attribute (:copier common-lisp:nil))
   (name common-lisp:nil :type
    (common-lisp:or engine-attribute-name common-lisp:null))
   (value common-lisp:nil :type
    (common-lisp:or engine-attribute-value common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'engine-attribute 'make-engine-attribute))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape engine-attribute))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Name"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'name)))
    (aws-sdk/generator/shape::to-query-params "Value"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'value))))))
(common-lisp:deftype engine-attribute-name () 'common-lisp:string)
(common-lisp:deftype engine-attribute-value () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype engine-attributes ()
   '(trivial-types:proper-list engine-attribute))
 (common-lisp:defun |make-engine-attributes|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list engine-attribute))
   aws-sdk/generator/shape::members))
(common-lisp:deftype instance-profile-arn () 'common-lisp:string)
(common-lisp:deftype integer () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:defstruct
     (invalid-next-token-exception (:copier common-lisp:nil))
   (message common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'invalid-next-token-exception
                    'make-invalid-next-token-exception))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          invalid-next-token-exception))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Message"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'message))))))
(common-lisp:progn
 (common-lisp:defstruct (invalid-state-exception (:copier common-lisp:nil))
   (message common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'invalid-state-exception 'make-invalid-state-exception))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          invalid-state-exception))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Message"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'message))))))
(common-lisp:deftype key-pair () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (limit-exceeded-exception (:copier common-lisp:nil))
   (message common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'limit-exceeded-exception 'make-limit-exceeded-exception))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          limit-exceeded-exception))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Message"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'message))))))
(common-lisp:deftype maintenance-status () 'common-lisp:string)
(common-lisp:deftype max-results () 'common-lisp:integer)
(common-lisp:deftype next-token () 'common-lisp:string)
(common-lisp:deftype node-association-status () 'common-lisp:string)
(common-lisp:deftype node-association-status-token () 'common-lisp:string)
(common-lisp:deftype node-name () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct
     (resource-already-exists-exception (:copier common-lisp:nil))
   (message common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'resource-already-exists-exception
                    'make-resource-already-exists-exception))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          resource-already-exists-exception))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Message"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'message))))))
(common-lisp:progn
 (common-lisp:defstruct
     (resource-not-found-exception (:copier common-lisp:nil))
   (message common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'resource-not-found-exception
                    'make-resource-not-found-exception))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          resource-not-found-exception))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Message"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'message))))))
(common-lisp:progn
 (common-lisp:defstruct (restore-server-request (:copier common-lisp:nil))
   (backup-id (common-lisp:error ":backup-id is required") :type
    (common-lisp:or backup-id common-lisp:null))
   (server-name (common-lisp:error ":server-name is required") :type
    (common-lisp:or server-name common-lisp:null))
   (instance-type common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (key-pair common-lisp:nil :type (common-lisp:or key-pair common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'restore-server-request 'make-restore-server-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          restore-server-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "BackupId"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'backup-id)))
    (aws-sdk/generator/shape::to-query-params "ServerName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server-name)))
    (aws-sdk/generator/shape::to-query-params "InstanceType"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'instance-type)))
    (aws-sdk/generator/shape::to-query-params "KeyPair"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'key-pair))))))
(common-lisp:progn
 (common-lisp:defstruct (restore-server-response (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'restore-server-response 'make-restore-server-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          restore-server-response))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct (server (:copier common-lisp:nil))
   (associate-public-ip-address common-lisp:nil :type
    (common-lisp:or boolean common-lisp:null))
   (backup-retention-count common-lisp:nil :type
    (common-lisp:or integer common-lisp:null))
   (server-name common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (created-at common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (cloud-formation-stack-arn common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (disable-automated-backup common-lisp:nil :type
    (common-lisp:or boolean common-lisp:null))
   (endpoint common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (engine common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (engine-model common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (engine-attributes common-lisp:nil :type
    (common-lisp:or engine-attributes common-lisp:null))
   (engine-version common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (instance-profile-arn common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (instance-type common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (key-pair common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (maintenance-status common-lisp:nil :type
    (common-lisp:or maintenance-status common-lisp:null))
   (preferred-maintenance-window common-lisp:nil :type
    (common-lisp:or time-window-definition common-lisp:null))
   (preferred-backup-window common-lisp:nil :type
    (common-lisp:or time-window-definition common-lisp:null))
   (security-group-ids common-lisp:nil :type
    (common-lisp:or strings common-lisp:null))
   (service-role-arn common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (status common-lisp:nil :type
    (common-lisp:or server-status common-lisp:null))
   (status-reason common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (subnet-ids common-lisp:nil :type (common-lisp:or strings common-lisp:null))
   (server-arn common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export (common-lisp:list 'server 'make-server))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape server))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "AssociatePublicIpAddress"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'associate-public-ip-address)))
    (aws-sdk/generator/shape::to-query-params "BackupRetentionCount"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'backup-retention-count)))
    (aws-sdk/generator/shape::to-query-params "ServerName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server-name)))
    (aws-sdk/generator/shape::to-query-params "CreatedAt"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'created-at)))
    (aws-sdk/generator/shape::to-query-params "CloudFormationStackArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'cloud-formation-stack-arn)))
    (aws-sdk/generator/shape::to-query-params "DisableAutomatedBackup"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'disable-automated-backup)))
    (aws-sdk/generator/shape::to-query-params "Endpoint"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'endpoint)))
    (aws-sdk/generator/shape::to-query-params "Engine"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'engine)))
    (aws-sdk/generator/shape::to-query-params "EngineModel"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'engine-model)))
    (aws-sdk/generator/shape::to-query-params "EngineAttributes"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'engine-attributes)))
    (aws-sdk/generator/shape::to-query-params "EngineVersion"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'engine-version)))
    (aws-sdk/generator/shape::to-query-params "InstanceProfileArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'instance-profile-arn)))
    (aws-sdk/generator/shape::to-query-params "InstanceType"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'instance-type)))
    (aws-sdk/generator/shape::to-query-params "KeyPair"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'key-pair)))
    (aws-sdk/generator/shape::to-query-params "MaintenanceStatus"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'maintenance-status)))
    (aws-sdk/generator/shape::to-query-params "PreferredMaintenanceWindow"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'preferred-maintenance-window)))
    (aws-sdk/generator/shape::to-query-params "PreferredBackupWindow"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'preferred-backup-window)))
    (aws-sdk/generator/shape::to-query-params "SecurityGroupIds"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'security-group-ids)))
    (aws-sdk/generator/shape::to-query-params "ServiceRoleArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'service-role-arn)))
    (aws-sdk/generator/shape::to-query-params "Status"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'status)))
    (aws-sdk/generator/shape::to-query-params "StatusReason"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'status-reason)))
    (aws-sdk/generator/shape::to-query-params "SubnetIds"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'subnet-ids)))
    (aws-sdk/generator/shape::to-query-params "ServerArn"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server-arn))))))
(common-lisp:progn
 (common-lisp:defstruct (server-event (:copier common-lisp:nil))
   (created-at common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (server-name common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (message common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (log-url common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export (common-lisp:list 'server-event 'make-server-event))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape server-event))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "CreatedAt"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'created-at)))
    (aws-sdk/generator/shape::to-query-params "ServerName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server-name)))
    (aws-sdk/generator/shape::to-query-params "Message"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'message)))
    (aws-sdk/generator/shape::to-query-params "LogUrl"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'log-url))))))
(common-lisp:progn
 (common-lisp:deftype server-events ()
   '(trivial-types:proper-list server-event))
 (common-lisp:defun |make-server-events|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list server-event))
   aws-sdk/generator/shape::members))
(common-lisp:deftype server-name () 'common-lisp:string)
(common-lisp:deftype server-status () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype servers () '(trivial-types:proper-list server))
 (common-lisp:defun |make-servers|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list server))
   aws-sdk/generator/shape::members))
(common-lisp:deftype service-role-arn () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (start-maintenance-request (:copier common-lisp:nil))
   (server-name (common-lisp:error ":server-name is required") :type
    (common-lisp:or server-name common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'start-maintenance-request
                    'make-start-maintenance-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          start-maintenance-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ServerName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server-name))))))
(common-lisp:progn
 (common-lisp:defstruct (start-maintenance-response (:copier common-lisp:nil))
   (server common-lisp:nil :type (common-lisp:or server common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'start-maintenance-response
                    'make-start-maintenance-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          start-maintenance-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Server"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server))))))
(common-lisp:deftype string () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype strings () '(trivial-types:proper-list string))
 (common-lisp:defun |make-strings|
                    (common-lisp:&rest aws-sdk/generator/shape::members)
   (common-lisp:check-type aws-sdk/generator/shape::members
                           (trivial-types:proper-list string))
   aws-sdk/generator/shape::members))
(common-lisp:deftype time-window-definition () 'common-lisp:string)
(common-lisp:deftype timestamp () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct
     (update-server-engine-attributes-request (:copier common-lisp:nil))
   (server-name (common-lisp:error ":server-name is required") :type
    (common-lisp:or server-name common-lisp:null))
   (attribute-name (common-lisp:error ":attribute-name is required") :type
    (common-lisp:or attribute-name common-lisp:null))
   (attribute-value common-lisp:nil :type
    (common-lisp:or attribute-value common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'update-server-engine-attributes-request
                    'make-update-server-engine-attributes-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          update-server-engine-attributes-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "ServerName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server-name)))
    (aws-sdk/generator/shape::to-query-params "AttributeName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'attribute-name)))
    (aws-sdk/generator/shape::to-query-params "AttributeValue"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'attribute-value))))))
(common-lisp:progn
 (common-lisp:defstruct
     (update-server-engine-attributes-response (:copier common-lisp:nil))
   (server common-lisp:nil :type (common-lisp:or server common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'update-server-engine-attributes-response
                    'make-update-server-engine-attributes-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          update-server-engine-attributes-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Server"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server))))))
(common-lisp:progn
 (common-lisp:defstruct (update-server-request (:copier common-lisp:nil))
   (disable-automated-backup common-lisp:nil :type
    (common-lisp:or boolean common-lisp:null))
   (backup-retention-count common-lisp:nil :type
    (common-lisp:or integer common-lisp:null))
   (server-name (common-lisp:error ":server-name is required") :type
    (common-lisp:or server-name common-lisp:null))
   (preferred-maintenance-window common-lisp:nil :type
    (common-lisp:or time-window-definition common-lisp:null))
   (preferred-backup-window common-lisp:nil :type
    (common-lisp:or time-window-definition common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'update-server-request 'make-update-server-request))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          update-server-request))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "DisableAutomatedBackup"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'disable-automated-backup)))
    (aws-sdk/generator/shape::to-query-params "BackupRetentionCount"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'backup-retention-count)))
    (aws-sdk/generator/shape::to-query-params "ServerName"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server-name)))
    (aws-sdk/generator/shape::to-query-params "PreferredMaintenanceWindow"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'preferred-maintenance-window)))
    (aws-sdk/generator/shape::to-query-params "PreferredBackupWindow"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'preferred-backup-window))))))
(common-lisp:progn
 (common-lisp:defstruct (update-server-response (:copier common-lisp:nil))
   (server common-lisp:nil :type (common-lisp:or server common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'update-server-response 'make-update-server-response))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        (
                         (aws-sdk/generator/shape::shape
                          update-server-response))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Server"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'server))))))
(common-lisp:progn
 (common-lisp:defstruct (validation-exception (:copier common-lisp:nil))
   (message common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'validation-exception 'make-validation-exception))
 (common-lisp:defmethod aws-sdk/generator/shape:shape-to-params
                        ((aws-sdk/generator/shape::shape validation-exception))
   (common-lisp:append
    (aws-sdk/generator/shape::to-query-params "Message"
                                              (aws-sdk/generator/shape:shape-to-params
                                               (common-lisp:slot-value
                                                aws-sdk/generator/shape::shape
                                                'message))))))
(common-lisp:progn
 (common-lisp:defun associate-node
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key server-name node-name engine-attributes)
   (common-lisp:declare
    (common-lisp:ignorable server-name node-name engine-attributes))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-associate-node-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (common-lisp:make-instance 'opsworkscm-request :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"AssociateNode")
                                     ("Version" ,@"2016-11-01"))
                                   (aws-sdk/generator/shape:shape-to-params
                                    aws-sdk/generator/operation::input))))
      "AssociateNodeResponse" common-lisp:nil)))
 (common-lisp:export 'associate-node))
(common-lisp:progn
 (common-lisp:defun create-backup
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key server-name description)
   (common-lisp:declare (common-lisp:ignorable server-name description))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-create-backup-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (common-lisp:make-instance 'opsworkscm-request :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"CreateBackup")
                                     ("Version" ,@"2016-11-01"))
                                   (aws-sdk/generator/shape:shape-to-params
                                    aws-sdk/generator/operation::input))))
      "CreateBackupResponse" common-lisp:nil)))
 (common-lisp:export 'create-backup))
(common-lisp:progn
 (common-lisp:defun create-server
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key associate-public-ip-address
                     disable-automated-backup engine engine-model
                     engine-version engine-attributes backup-retention-count
                     server-name instance-profile-arn instance-type key-pair
                     preferred-maintenance-window preferred-backup-window
                     security-group-ids service-role-arn subnet-ids backup-id)
   (common-lisp:declare
    (common-lisp:ignorable associate-public-ip-address disable-automated-backup
     engine engine-model engine-version engine-attributes
     backup-retention-count server-name instance-profile-arn instance-type
     key-pair preferred-maintenance-window preferred-backup-window
     security-group-ids service-role-arn subnet-ids backup-id))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-create-server-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (common-lisp:make-instance 'opsworkscm-request :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"CreateServer")
                                     ("Version" ,@"2016-11-01"))
                                   (aws-sdk/generator/shape:shape-to-params
                                    aws-sdk/generator/operation::input))))
      "CreateServerResponse" common-lisp:nil)))
 (common-lisp:export 'create-server))
(common-lisp:progn
 (common-lisp:defun delete-backup
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key backup-id)
   (common-lisp:declare (common-lisp:ignorable backup-id))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-delete-backup-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (common-lisp:make-instance 'opsworkscm-request :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"DeleteBackup")
                                     ("Version" ,@"2016-11-01"))
                                   (aws-sdk/generator/shape:shape-to-params
                                    aws-sdk/generator/operation::input))))
      "DeleteBackupResponse" common-lisp:nil)))
 (common-lisp:export 'delete-backup))
(common-lisp:progn
 (common-lisp:defun delete-server
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key server-name)
   (common-lisp:declare (common-lisp:ignorable server-name))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-delete-server-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (common-lisp:make-instance 'opsworkscm-request :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"DeleteServer")
                                     ("Version" ,@"2016-11-01"))
                                   (aws-sdk/generator/shape:shape-to-params
                                    aws-sdk/generator/operation::input))))
      "DeleteServerResponse" common-lisp:nil)))
 (common-lisp:export 'delete-server))
(common-lisp:progn
 (common-lisp:defun describe-account-attributes ()
   (aws-sdk/generator/operation::parse-response
    (aws-sdk/api:aws-request
     (common-lisp:make-instance 'opsworkscm-request :method :post :params
                                (common-lisp:cons "Action"
                                                  "DescribeAccountAttributes")))
    "DescribeAccountAttributesResponse" common-lisp:nil))
 (common-lisp:export 'describe-account-attributes))
(common-lisp:progn
 (common-lisp:defun describe-backups
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key backup-id server-name next-token
                     max-results)
   (common-lisp:declare
    (common-lisp:ignorable backup-id server-name next-token max-results))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-describe-backups-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (common-lisp:make-instance 'opsworkscm-request :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"DescribeBackups")
                                     ("Version" ,@"2016-11-01"))
                                   (aws-sdk/generator/shape:shape-to-params
                                    aws-sdk/generator/operation::input))))
      "DescribeBackupsResponse" common-lisp:nil)))
 (common-lisp:export 'describe-backups))
(common-lisp:progn
 (common-lisp:defun describe-events
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key server-name next-token max-results)
   (common-lisp:declare
    (common-lisp:ignorable server-name next-token max-results))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-describe-events-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (common-lisp:make-instance 'opsworkscm-request :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"DescribeEvents")
                                     ("Version" ,@"2016-11-01"))
                                   (aws-sdk/generator/shape:shape-to-params
                                    aws-sdk/generator/operation::input))))
      "DescribeEventsResponse" common-lisp:nil)))
 (common-lisp:export 'describe-events))
(common-lisp:progn
 (common-lisp:defun describe-node-association-status
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key node-association-status-token
                     server-name)
   (common-lisp:declare
    (common-lisp:ignorable node-association-status-token server-name))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply
                       'make-describe-node-association-status-request
                       aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (common-lisp:make-instance 'opsworkscm-request :method :post :params
                                  (common-lisp:append
                                   `(("Action"
                                      ,@"DescribeNodeAssociationStatus")
                                     ("Version" ,@"2016-11-01"))
                                   (aws-sdk/generator/shape:shape-to-params
                                    aws-sdk/generator/operation::input))))
      "DescribeNodeAssociationStatusResponse" common-lisp:nil)))
 (common-lisp:export 'describe-node-association-status))
(common-lisp:progn
 (common-lisp:defun describe-servers
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key server-name next-token max-results)
   (common-lisp:declare
    (common-lisp:ignorable server-name next-token max-results))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-describe-servers-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (common-lisp:make-instance 'opsworkscm-request :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"DescribeServers")
                                     ("Version" ,@"2016-11-01"))
                                   (aws-sdk/generator/shape:shape-to-params
                                    aws-sdk/generator/operation::input))))
      "DescribeServersResponse" common-lisp:nil)))
 (common-lisp:export 'describe-servers))
(common-lisp:progn
 (common-lisp:defun disassociate-node
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key server-name node-name engine-attributes)
   (common-lisp:declare
    (common-lisp:ignorable server-name node-name engine-attributes))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-disassociate-node-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (common-lisp:make-instance 'opsworkscm-request :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"DisassociateNode")
                                     ("Version" ,@"2016-11-01"))
                                   (aws-sdk/generator/shape:shape-to-params
                                    aws-sdk/generator/operation::input))))
      "DisassociateNodeResponse" common-lisp:nil)))
 (common-lisp:export 'disassociate-node))
(common-lisp:progn
 (common-lisp:defun restore-server
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key backup-id server-name instance-type
                     key-pair)
   (common-lisp:declare
    (common-lisp:ignorable backup-id server-name instance-type key-pair))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-restore-server-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (common-lisp:make-instance 'opsworkscm-request :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"RestoreServer")
                                     ("Version" ,@"2016-11-01"))
                                   (aws-sdk/generator/shape:shape-to-params
                                    aws-sdk/generator/operation::input))))
      "RestoreServerResponse" common-lisp:nil)))
 (common-lisp:export 'restore-server))
(common-lisp:progn
 (common-lisp:defun start-maintenance
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key server-name)
   (common-lisp:declare (common-lisp:ignorable server-name))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-start-maintenance-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (common-lisp:make-instance 'opsworkscm-request :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"StartMaintenance")
                                     ("Version" ,@"2016-11-01"))
                                   (aws-sdk/generator/shape:shape-to-params
                                    aws-sdk/generator/operation::input))))
      "StartMaintenanceResponse" common-lisp:nil)))
 (common-lisp:export 'start-maintenance))
(common-lisp:progn
 (common-lisp:defun update-server
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key disable-automated-backup
                     backup-retention-count server-name
                     preferred-maintenance-window preferred-backup-window)
   (common-lisp:declare
    (common-lisp:ignorable disable-automated-backup backup-retention-count
     server-name preferred-maintenance-window preferred-backup-window))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply 'make-update-server-request
                                         aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (common-lisp:make-instance 'opsworkscm-request :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"UpdateServer")
                                     ("Version" ,@"2016-11-01"))
                                   (aws-sdk/generator/shape:shape-to-params
                                    aws-sdk/generator/operation::input))))
      "UpdateServerResponse" common-lisp:nil)))
 (common-lisp:export 'update-server))
(common-lisp:progn
 (common-lisp:defun update-server-engine-attributes
                    (
                     common-lisp:&rest aws-sdk/generator/operation::args
                     common-lisp:&key server-name attribute-name
                     attribute-value)
   (common-lisp:declare
    (common-lisp:ignorable server-name attribute-name attribute-value))
   (common-lisp:let ((aws-sdk/generator/operation::input
                      (common-lisp:apply
                       'make-update-server-engine-attributes-request
                       aws-sdk/generator/operation::args)))
     (aws-sdk/generator/operation::parse-response
      (aws-sdk/api:aws-request
       (common-lisp:make-instance 'opsworkscm-request :method :post :params
                                  (common-lisp:append
                                   `(("Action"
                                      ,@"UpdateServerEngineAttributes")
                                     ("Version" ,@"2016-11-01"))
                                   (aws-sdk/generator/shape:shape-to-params
                                    aws-sdk/generator/operation::input))))
      "UpdateServerEngineAttributesResponse" common-lisp:nil)))
 (common-lisp:export 'update-server-engine-attributes))
